// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: autocomplete.sql

package sqlc

import (
	"context"
)

const listCommentAutocompleteReferences = `-- name: ListCommentAutocompleteReferences :many
SELECT kind, number, title, state
FROM (
    SELECT 'pull' AS kind,
           mr.number,
           mr.title,
           mr.state,
           mr.last_activity_at,
           CASE
               WHEN ?1 <> ''
                    AND CAST(mr.number AS TEXT) LIKE CAST(?2 AS TEXT)
               THEN 0
               ELSE 1
           END AS number_rank,
           CASE
               WHEN ?1 <> ''
                    AND LOWER(mr.title) LIKE ?3
               THEN 0
               ELSE 1
           END AS title_rank
    FROM middleman_merge_requests mr
    WHERE mr.repo_id = ?4
      AND (
          ?1 = ''
          OR CAST(mr.number AS TEXT) LIKE CAST(?2 AS TEXT)
          OR LOWER(mr.title) LIKE ?3
      )
    UNION ALL
    SELECT 'issue' AS kind,
           i.number,
           i.title,
           i.state,
           i.last_activity_at,
           CASE
               WHEN ?1 <> ''
                    AND CAST(i.number AS TEXT) LIKE CAST(?2 AS TEXT)
               THEN 0
               ELSE 1
           END AS number_rank,
           CASE
               WHEN ?1 <> ''
                    AND LOWER(i.title) LIKE ?3
               THEN 0
               ELSE 1
           END AS title_rank
    FROM middleman_issues i
    WHERE i.repo_id = ?4
      AND (
          ?1 = ''
          OR CAST(i.number AS TEXT) LIKE CAST(?2 AS TEXT)
          OR LOWER(i.title) LIKE ?3
      )
)
ORDER BY
    number_rank,
    title_rank,
    last_activity_at DESC,
    number DESC
LIMIT ?5
`

type ListCommentAutocompleteReferencesParams struct {
	Query        interface{}
	NumberPrefix string
	TitleQuery   string
	RepoID       int64
	Limit        int64
}

type ListCommentAutocompleteReferencesRow struct {
	Kind   string
	Number int64
	Title  string
	State  string
}

func (q *Queries) ListCommentAutocompleteReferences(ctx context.Context, arg ListCommentAutocompleteReferencesParams) ([]ListCommentAutocompleteReferencesRow, error) {
	rows, err := q.db.QueryContext(ctx, listCommentAutocompleteReferences,
		arg.Query,
		arg.NumberPrefix,
		arg.TitleQuery,
		arg.RepoID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCommentAutocompleteReferencesRow
	for rows.Next() {
		var i ListCommentAutocompleteReferencesRow
		if err := rows.Scan(
			&i.Kind,
			&i.Number,
			&i.Title,
			&i.State,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCommentAutocompleteUsers = `-- name: ListCommentAutocompleteUsers :many
SELECT login
FROM (
    SELECT mr.author AS login,
           mr.last_activity_at AS last_seen,
           CASE
               WHEN ?1 <> '' AND LOWER(mr.author) LIKE ?2 THEN 0
               ELSE 1
           END AS prefix_rank
    FROM middleman_merge_requests mr
    WHERE mr.repo_id = ?3
      AND mr.author <> ''
      AND (?1 = '' OR LOWER(mr.author) LIKE ?4)
    UNION ALL
    SELECT i.author AS login,
           i.last_activity_at AS last_seen,
           CASE
               WHEN ?1 <> '' AND LOWER(i.author) LIKE ?2 THEN 0
               ELSE 1
           END AS prefix_rank
    FROM middleman_issues i
    WHERE i.repo_id = ?3
      AND i.author <> ''
      AND (?1 = '' OR LOWER(i.author) LIKE ?4)
    UNION ALL
    SELECT e.author AS login,
           e.created_at AS last_seen,
           CASE
               WHEN ?1 <> '' AND LOWER(e.author) LIKE ?2 THEN 0
               ELSE 1
           END AS prefix_rank
    FROM middleman_mr_events e
    JOIN middleman_merge_requests mr ON mr.id = e.merge_request_id
    WHERE mr.repo_id = ?3
      AND e.author <> ''
      AND (?1 = '' OR LOWER(e.author) LIKE ?4)
    UNION ALL
    SELECT e.author AS login,
           e.created_at AS last_seen,
           CASE
               WHEN ?1 <> '' AND LOWER(e.author) LIKE ?2 THEN 0
               ELSE 1
           END AS prefix_rank
    FROM middleman_issue_events e
    JOIN middleman_issues i ON i.id = e.issue_id
    WHERE i.repo_id = ?3
      AND e.author <> ''
      AND (?1 = '' OR LOWER(e.author) LIKE ?4)
)
GROUP BY login
ORDER BY
    MIN(prefix_rank),
    MAX(last_seen) DESC,
    login ASC
LIMIT ?5
`

type ListCommentAutocompleteUsersParams struct {
	Query         interface{}
	PrefixQuery   string
	RepoID        int64
	ContainsQuery string
	Limit         int64
}

func (q *Queries) ListCommentAutocompleteUsers(ctx context.Context, arg ListCommentAutocompleteUsersParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listCommentAutocompleteUsers,
		arg.Query,
		arg.PrefixQuery,
		arg.RepoID,
		arg.ContainsQuery,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var login string
		if err := rows.Scan(&login); err != nil {
			return nil, err
		}
		items = append(items, login)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
