// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: issues.sql

package sqlc

import (
	"context"
	"database/sql"
	"strings"
	"time"
)

const deleteAllIssueCommentEvents = `-- name: DeleteAllIssueCommentEvents :exec
DELETE FROM middleman_issue_events
WHERE issue_id = ?1
  AND event_type = 'issue_comment'
`

func (q *Queries) DeleteAllIssueCommentEvents(ctx context.Context, issueID int64) error {
	_, err := q.db.ExecContext(ctx, deleteAllIssueCommentEvents, issueID)
	return err
}

const deleteMissingIssueCommentEvents = `-- name: DeleteMissingIssueCommentEvents :exec
DELETE FROM middleman_issue_events
WHERE issue_id = ?1
  AND event_type = 'issue_comment'
  AND dedupe_key NOT IN (/*SLICE:dedupe_keys*/?)
`

type DeleteMissingIssueCommentEventsParams struct {
	IssueID    int64
	DedupeKeys []string
}

func (q *Queries) DeleteMissingIssueCommentEvents(ctx context.Context, arg DeleteMissingIssueCommentEventsParams) error {
	query := deleteMissingIssueCommentEvents
	var queryParams []interface{}
	queryParams = append(queryParams, arg.IssueID)
	if len(arg.DedupeKeys) > 0 {
		for _, v := range arg.DedupeKeys {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:dedupe_keys*/?", strings.Repeat(",?", len(arg.DedupeKeys))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:dedupe_keys*/?", "NULL", 1)
	}
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}

const getIssueByOwnerNameNumber = `-- name: GetIssueByOwnerNameNumber :one
SELECT i.id, i.repo_id, i.platform_id, i.number, i.url, i.title,
       i.author, i.state, i.body, i.comment_count, i.labels_json,
       i.detail_fetched_at,
       i.created_at, i.updated_at, i.last_activity_at, i.closed_at,
       (s.number IS NOT NULL) AS starred
FROM middleman_issues i
JOIN middleman_repos r ON r.id = i.repo_id
LEFT JOIN middleman_starred_items s
    ON s.item_type = 'issue' AND s.repo_id = i.repo_id AND s.number = i.number
WHERE r.owner = ?1 AND r.name = ?2 AND i.number = ?3
`

type GetIssueByOwnerNameNumberParams struct {
	Owner  string
	Name   string
	Number int64
}

type GetIssueByOwnerNameNumberRow struct {
	ID              int64
	RepoID          int64
	PlatformID      int64
	Number          int64
	Url             string
	Title           string
	Author          string
	State           string
	Body            string
	CommentCount    int64
	LabelsJson      string
	DetailFetchedAt sql.NullTime
	CreatedAt       time.Time
	UpdatedAt       time.Time
	LastActivityAt  time.Time
	ClosedAt        sql.NullTime
	Starred         interface{}
}

func (q *Queries) GetIssueByOwnerNameNumber(ctx context.Context, arg GetIssueByOwnerNameNumberParams) (GetIssueByOwnerNameNumberRow, error) {
	row := q.db.QueryRowContext(ctx, getIssueByOwnerNameNumber, arg.Owner, arg.Name, arg.Number)
	var i GetIssueByOwnerNameNumberRow
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.PlatformID,
		&i.Number,
		&i.Url,
		&i.Title,
		&i.Author,
		&i.State,
		&i.Body,
		&i.CommentCount,
		&i.LabelsJson,
		&i.DetailFetchedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastActivityAt,
		&i.ClosedAt,
		&i.Starred,
	)
	return i, err
}

const getIssueByRepoIDAndNumber = `-- name: GetIssueByRepoIDAndNumber :one
SELECT i.id, i.repo_id, i.platform_id, i.number, i.url, i.title,
       i.author, i.state, i.body, i.comment_count, i.labels_json,
       i.detail_fetched_at,
       i.created_at, i.updated_at, i.last_activity_at, i.closed_at,
       (s.number IS NOT NULL) AS starred
FROM middleman_issues i
LEFT JOIN middleman_starred_items s
    ON s.item_type = 'issue' AND s.repo_id = i.repo_id AND s.number = i.number
WHERE i.repo_id = ?1 AND i.number = ?2
`

type GetIssueByRepoIDAndNumberParams struct {
	RepoID int64
	Number int64
}

type GetIssueByRepoIDAndNumberRow struct {
	ID              int64
	RepoID          int64
	PlatformID      int64
	Number          int64
	Url             string
	Title           string
	Author          string
	State           string
	Body            string
	CommentCount    int64
	LabelsJson      string
	DetailFetchedAt sql.NullTime
	CreatedAt       time.Time
	UpdatedAt       time.Time
	LastActivityAt  time.Time
	ClosedAt        sql.NullTime
	Starred         interface{}
}

func (q *Queries) GetIssueByRepoIDAndNumber(ctx context.Context, arg GetIssueByRepoIDAndNumberParams) (GetIssueByRepoIDAndNumberRow, error) {
	row := q.db.QueryRowContext(ctx, getIssueByRepoIDAndNumber, arg.RepoID, arg.Number)
	var i GetIssueByRepoIDAndNumberRow
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.PlatformID,
		&i.Number,
		&i.Url,
		&i.Title,
		&i.Author,
		&i.State,
		&i.Body,
		&i.CommentCount,
		&i.LabelsJson,
		&i.DetailFetchedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastActivityAt,
		&i.ClosedAt,
		&i.Starred,
	)
	return i, err
}

const getIssueIDByOwnerNameNumber = `-- name: GetIssueIDByOwnerNameNumber :one
SELECT i.id
FROM middleman_issues i
JOIN middleman_repos r ON r.id = i.repo_id
WHERE r.owner = ?1 AND r.name = ?2 AND i.number = ?3
`

type GetIssueIDByOwnerNameNumberParams struct {
	Owner  string
	Name   string
	Number int64
}

func (q *Queries) GetIssueIDByOwnerNameNumber(ctx context.Context, arg GetIssueIDByOwnerNameNumberParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getIssueIDByOwnerNameNumber, arg.Owner, arg.Name, arg.Number)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getIssueIDByRepoIDAndNumber = `-- name: GetIssueIDByRepoIDAndNumber :one
SELECT id
FROM middleman_issues
WHERE repo_id = ?1 AND number = ?2
`

type GetIssueIDByRepoIDAndNumberParams struct {
	RepoID int64
	Number int64
}

func (q *Queries) GetIssueIDByRepoIDAndNumber(ctx context.Context, arg GetIssueIDByRepoIDAndNumberParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getIssueIDByRepoIDAndNumber, arg.RepoID, arg.Number)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const issueCommentEventExists = `-- name: IssueCommentEventExists :one
SELECT EXISTS (
    SELECT 1
    FROM middleman_issue_events
    WHERE issue_id = ?1
      AND platform_id = ?2
      AND event_type = 'issue_comment'
)
`

type IssueCommentEventExistsParams struct {
	IssueID    int64
	PlatformID sql.NullInt64
}

func (q *Queries) IssueCommentEventExists(ctx context.Context, arg IssueCommentEventExistsParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, issueCommentEventExists, arg.IssueID, arg.PlatformID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listIssueEvents = `-- name: ListIssueEvents :many
SELECT id, issue_id, platform_id, event_type, author, summary, body,
       metadata_json, CAST(created_at AS TEXT) AS created_at, dedupe_key
FROM middleman_issue_events
WHERE issue_id = ?1
ORDER BY created_at DESC
`

type ListIssueEventsRow struct {
	ID           int64
	IssueID      int64
	PlatformID   sql.NullInt64
	EventType    string
	Author       string
	Summary      string
	Body         string
	MetadataJson string
	CreatedAt    string
	DedupeKey    string
}

func (q *Queries) ListIssueEvents(ctx context.Context, issueID int64) ([]ListIssueEventsRow, error) {
	rows, err := q.db.QueryContext(ctx, listIssueEvents, issueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListIssueEventsRow
	for rows.Next() {
		var i ListIssueEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.IssueID,
			&i.PlatformID,
			&i.EventType,
			&i.Author,
			&i.Summary,
			&i.Body,
			&i.MetadataJson,
			&i.CreatedAt,
			&i.DedupeKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenIssueNumbersByRepo = `-- name: ListOpenIssueNumbersByRepo :many
SELECT number
FROM middleman_issues
WHERE repo_id = ?1 AND state = 'open'
`

func (q *Queries) ListOpenIssueNumbersByRepo(ctx context.Context, repoID int64) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listOpenIssueNumbersByRepo, repoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var number int64
		if err := rows.Scan(&number); err != nil {
			return nil, err
		}
		items = append(items, number)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateIssueDerivedFields = `-- name: UpdateIssueDerivedFields :exec
UPDATE middleman_issues
SET comment_count = ?1,
    last_activity_at = ?2
WHERE repo_id = ?3 AND number = ?4
`

type UpdateIssueDerivedFieldsParams struct {
	CommentCount   int64
	LastActivityAt time.Time
	RepoID         int64
	Number         int64
}

func (q *Queries) UpdateIssueDerivedFields(ctx context.Context, arg UpdateIssueDerivedFieldsParams) error {
	_, err := q.db.ExecContext(ctx, updateIssueDerivedFields,
		arg.CommentCount,
		arg.LastActivityAt,
		arg.RepoID,
		arg.Number,
	)
	return err
}

const updateIssueDetailFetched = `-- name: UpdateIssueDetailFetched :exec
UPDATE middleman_issues
SET detail_fetched_at = datetime('now')
WHERE repo_id = (
    SELECT id FROM middleman_repos
    WHERE platform_host = ?1
      AND owner = ?2
      AND name = ?3
) AND number = ?4
`

type UpdateIssueDetailFetchedParams struct {
	PlatformHost string
	Owner        string
	Name         string
	Number       int64
}

func (q *Queries) UpdateIssueDetailFetched(ctx context.Context, arg UpdateIssueDetailFetchedParams) error {
	_, err := q.db.ExecContext(ctx, updateIssueDetailFetched,
		arg.PlatformHost,
		arg.Owner,
		arg.Name,
		arg.Number,
	)
	return err
}

const updateIssueState = `-- name: UpdateIssueState :exec
UPDATE middleman_issues
SET state = ?1,
    closed_at = ?2,
    updated_at = ?3,
    last_activity_at = ?4
WHERE repo_id = ?5 AND number = ?6
`

type UpdateIssueStateParams struct {
	State          string
	ClosedAt       sql.NullTime
	UpdatedAt      time.Time
	LastActivityAt time.Time
	RepoID         int64
	Number         int64
}

func (q *Queries) UpdateIssueState(ctx context.Context, arg UpdateIssueStateParams) error {
	_, err := q.db.ExecContext(ctx, updateIssueState,
		arg.State,
		arg.ClosedAt,
		arg.UpdatedAt,
		arg.LastActivityAt,
		arg.RepoID,
		arg.Number,
	)
	return err
}

const upsertIssue = `-- name: UpsertIssue :exec
INSERT INTO middleman_issues (
    repo_id, platform_id, number, url, title, author, state,
    body, comment_count, labels_json, detail_fetched_at,
    created_at, updated_at, last_activity_at, closed_at
)
VALUES (
    ?1, ?2, ?3,
    ?4, ?5, ?6, ?7,
    ?8, ?9, ?10,
    ?11, ?12,
    ?13, ?14, ?15
)
ON CONFLICT(repo_id, number) DO UPDATE SET
    platform_id       = excluded.platform_id,
    url               = excluded.url,
    title             = excluded.title,
    author            = excluded.author,
    state             = excluded.state,
    body              = excluded.body,
    comment_count     = excluded.comment_count,
    labels_json       = excluded.labels_json,
    detail_fetched_at = COALESCE(middleman_issues.detail_fetched_at, excluded.detail_fetched_at),
    updated_at        = excluded.updated_at,
    last_activity_at  = excluded.last_activity_at,
    closed_at         = excluded.closed_at
WHERE excluded.updated_at >= middleman_issues.updated_at
`

type UpsertIssueParams struct {
	RepoID          int64
	PlatformID      int64
	Number          int64
	Url             string
	Title           string
	Author          string
	State           string
	Body            string
	CommentCount    int64
	LabelsJson      string
	DetailFetchedAt sql.NullTime
	CreatedAt       time.Time
	UpdatedAt       time.Time
	LastActivityAt  time.Time
	ClosedAt        sql.NullTime
}

func (q *Queries) UpsertIssue(ctx context.Context, arg UpsertIssueParams) error {
	_, err := q.db.ExecContext(ctx, upsertIssue,
		arg.RepoID,
		arg.PlatformID,
		arg.Number,
		arg.Url,
		arg.Title,
		arg.Author,
		arg.State,
		arg.Body,
		arg.CommentCount,
		arg.LabelsJson,
		arg.DetailFetchedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.LastActivityAt,
		arg.ClosedAt,
	)
	return err
}

const upsertIssueEvent = `-- name: UpsertIssueEvent :exec
INSERT INTO middleman_issue_events (
    issue_id, platform_id, event_type, author, summary, body,
    metadata_json, created_at, dedupe_key
)
VALUES (
    ?1, ?2, ?3,
    ?4, ?5, ?6, ?7,
    ?8, ?9
)
ON CONFLICT(dedupe_key) DO UPDATE SET
    issue_id       = excluded.issue_id,
    platform_id    = excluded.platform_id,
    event_type     = excluded.event_type,
    author         = excluded.author,
    summary        = excluded.summary,
    body           = excluded.body,
    metadata_json  = excluded.metadata_json,
    created_at     = excluded.created_at
`

type UpsertIssueEventParams struct {
	IssueID      int64
	PlatformID   sql.NullInt64
	EventType    string
	Author       string
	Summary      string
	Body         string
	MetadataJson string
	CreatedAt    time.Time
	DedupeKey    string
}

func (q *Queries) UpsertIssueEvent(ctx context.Context, arg UpsertIssueEventParams) error {
	_, err := q.db.ExecContext(ctx, upsertIssueEvent,
		arg.IssueID,
		arg.PlatformID,
		arg.EventType,
		arg.Author,
		arg.Summary,
		arg.Body,
		arg.MetadataJson,
		arg.CreatedAt,
		arg.DedupeKey,
	)
	return err
}
