// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: kanban.sql

package sqlc

import (
	"context"
)

const ensureKanbanState = `-- name: EnsureKanbanState :exec
INSERT INTO middleman_kanban_state (merge_request_id, status)
VALUES (?1, 'new')
ON CONFLICT(merge_request_id) DO NOTHING
`

func (q *Queries) EnsureKanbanState(ctx context.Context, mergeRequestID int64) error {
	_, err := q.db.ExecContext(ctx, ensureKanbanState, mergeRequestID)
	return err
}

const getKanbanState = `-- name: GetKanbanState :one
SELECT merge_request_id, status, updated_at
FROM middleman_kanban_state
WHERE merge_request_id = ?1
`

func (q *Queries) GetKanbanState(ctx context.Context, mergeRequestID int64) (MiddlemanKanbanState, error) {
	row := q.db.QueryRowContext(ctx, getKanbanState, mergeRequestID)
	var i MiddlemanKanbanState
	err := row.Scan(&i.MergeRequestID, &i.Status, &i.UpdatedAt)
	return i, err
}

const setKanbanState = `-- name: SetKanbanState :exec
INSERT INTO middleman_kanban_state (merge_request_id, status, updated_at)
VALUES (?1, ?2, datetime('now'))
ON CONFLICT(merge_request_id) DO UPDATE SET
    status = excluded.status,
    updated_at = excluded.updated_at
`

type SetKanbanStateParams struct {
	MergeRequestID int64
	Status         string
}

func (q *Queries) SetKanbanState(ctx context.Context, arg SetKanbanStateParams) error {
	_, err := q.db.ExecContext(ctx, setKanbanState, arg.MergeRequestID, arg.Status)
	return err
}
