// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: labels.sql

package sqlc

import (
	"context"
	"database/sql"
	"strings"
	"time"
)

const deleteIssueLabelAssociationsByLabel = `-- name: DeleteIssueLabelAssociationsByLabel :exec
DELETE FROM middleman_issue_labels
WHERE label_id = ?1
`

func (q *Queries) DeleteIssueLabelAssociationsByLabel(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteIssueLabelAssociationsByLabel, id)
	return err
}

const deleteIssueLabelsByIssueID = `-- name: DeleteIssueLabelsByIssueID :exec
DELETE FROM middleman_issue_labels
WHERE issue_id = ?1
`

func (q *Queries) DeleteIssueLabelsByIssueID(ctx context.Context, issueID int64) error {
	_, err := q.db.ExecContext(ctx, deleteIssueLabelsByIssueID, issueID)
	return err
}

const deleteLabelByID = `-- name: DeleteLabelByID :exec
DELETE FROM middleman_labels
WHERE id = ?1
`

func (q *Queries) DeleteLabelByID(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteLabelByID, id)
	return err
}

const deleteMergeRequestLabelAssociationsByLabel = `-- name: DeleteMergeRequestLabelAssociationsByLabel :exec
DELETE FROM middleman_merge_request_labels
WHERE label_id = ?1
`

func (q *Queries) DeleteMergeRequestLabelAssociationsByLabel(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteMergeRequestLabelAssociationsByLabel, id)
	return err
}

const deleteMergeRequestLabelsByMRID = `-- name: DeleteMergeRequestLabelsByMRID :exec
DELETE FROM middleman_merge_request_labels
WHERE merge_request_id = ?1
`

func (q *Queries) DeleteMergeRequestLabelsByMRID(ctx context.Context, mergeRequestID int64) error {
	_, err := q.db.ExecContext(ctx, deleteMergeRequestLabelsByMRID, mergeRequestID)
	return err
}

const getIssueRepoID = `-- name: GetIssueRepoID :one
SELECT repo_id
FROM middleman_issues
WHERE id = ?1
`

func (q *Queries) GetIssueRepoID(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getIssueRepoID, id)
	var repo_id int64
	err := row.Scan(&repo_id)
	return repo_id, err
}

const getLabelPlatformID = `-- name: GetLabelPlatformID :one
SELECT platform_id
FROM middleman_labels
WHERE id = ?1
`

func (q *Queries) GetLabelPlatformID(ctx context.Context, id int64) (sql.NullInt64, error) {
	row := q.db.QueryRowContext(ctx, getLabelPlatformID, id)
	var platform_id sql.NullInt64
	err := row.Scan(&platform_id)
	return platform_id, err
}

const getMergeRequestRepoID = `-- name: GetMergeRequestRepoID :one
SELECT repo_id
FROM middleman_merge_requests
WHERE id = ?1
`

func (q *Queries) GetMergeRequestRepoID(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getMergeRequestRepoID, id)
	var repo_id int64
	err := row.Scan(&repo_id)
	return repo_id, err
}

const insertIssueLabel = `-- name: InsertIssueLabel :exec
INSERT INTO middleman_issue_labels (issue_id, label_id)
VALUES (?1, ?2)
ON CONFLICT(issue_id, label_id) DO NOTHING
`

type InsertIssueLabelParams struct {
	IssueID int64
	LabelID int64
}

func (q *Queries) InsertIssueLabel(ctx context.Context, arg InsertIssueLabelParams) error {
	_, err := q.db.ExecContext(ctx, insertIssueLabel, arg.IssueID, arg.LabelID)
	return err
}

const insertLabel = `-- name: InsertLabel :execlastid
INSERT INTO middleman_labels (
    repo_id, platform_id, name, description, color, is_default, updated_at
)
VALUES (
    ?1,
    NULLIF(?2, 0),
    ?3,
    ?4,
    ?5,
    ?6,
    ?7
)
`

type InsertLabelParams struct {
	RepoID      int64
	PlatformID  interface{}
	Name        string
	Description string
	Color       string
	IsDefault   int64
	UpdatedAt   time.Time
}

func (q *Queries) InsertLabel(ctx context.Context, arg InsertLabelParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertLabel,
		arg.RepoID,
		arg.PlatformID,
		arg.Name,
		arg.Description,
		arg.Color,
		arg.IsDefault,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const insertMergeRequestLabel = `-- name: InsertMergeRequestLabel :exec
INSERT INTO middleman_merge_request_labels (merge_request_id, label_id)
VALUES (?1, ?2)
ON CONFLICT(merge_request_id, label_id) DO NOTHING
`

type InsertMergeRequestLabelParams struct {
	MergeRequestID int64
	LabelID        int64
}

func (q *Queries) InsertMergeRequestLabel(ctx context.Context, arg InsertMergeRequestLabelParams) error {
	_, err := q.db.ExecContext(ctx, insertMergeRequestLabel, arg.MergeRequestID, arg.LabelID)
	return err
}

const listLabelsForIssueIDs = `-- name: ListLabelsForIssueIDs :many
SELECT il.issue_id, l.id, l.repo_id, COALESCE(l.platform_id, 0) AS platform_id,
       l.name, l.description, l.color, l.is_default, l.updated_at
FROM middleman_issue_labels il
JOIN middleman_labels l ON l.id = il.label_id
WHERE il.issue_id IN (/*SLICE:issue_ids*/?)
ORDER BY l.name, l.id
`

type ListLabelsForIssueIDsRow struct {
	IssueID     int64
	ID          int64
	RepoID      int64
	PlatformID  int64
	Name        string
	Description string
	Color       string
	IsDefault   int64
	UpdatedAt   time.Time
}

func (q *Queries) ListLabelsForIssueIDs(ctx context.Context, issueIds []int64) ([]ListLabelsForIssueIDsRow, error) {
	query := listLabelsForIssueIDs
	var queryParams []interface{}
	if len(issueIds) > 0 {
		for _, v := range issueIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:issue_ids*/?", strings.Repeat(",?", len(issueIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:issue_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLabelsForIssueIDsRow
	for rows.Next() {
		var i ListLabelsForIssueIDsRow
		if err := rows.Scan(
			&i.IssueID,
			&i.ID,
			&i.RepoID,
			&i.PlatformID,
			&i.Name,
			&i.Description,
			&i.Color,
			&i.IsDefault,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLabelsForMergeRequestIDs = `-- name: ListLabelsForMergeRequestIDs :many
SELECT ml.merge_request_id, l.id, l.repo_id, COALESCE(l.platform_id, 0) AS platform_id,
       l.name, l.description, l.color, l.is_default, l.updated_at
FROM middleman_merge_request_labels ml
JOIN middleman_labels l ON l.id = ml.label_id
WHERE ml.merge_request_id IN (/*SLICE:merge_request_ids*/?)
ORDER BY l.name, l.id
`

type ListLabelsForMergeRequestIDsRow struct {
	MergeRequestID int64
	ID             int64
	RepoID         int64
	PlatformID     int64
	Name           string
	Description    string
	Color          string
	IsDefault      int64
	UpdatedAt      time.Time
}

func (q *Queries) ListLabelsForMergeRequestIDs(ctx context.Context, mergeRequestIds []int64) ([]ListLabelsForMergeRequestIDsRow, error) {
	query := listLabelsForMergeRequestIDs
	var queryParams []interface{}
	if len(mergeRequestIds) > 0 {
		for _, v := range mergeRequestIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:merge_request_ids*/?", strings.Repeat(",?", len(mergeRequestIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:merge_request_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLabelsForMergeRequestIDsRow
	for rows.Next() {
		var i ListLabelsForMergeRequestIDsRow
		if err := rows.Scan(
			&i.MergeRequestID,
			&i.ID,
			&i.RepoID,
			&i.PlatformID,
			&i.Name,
			&i.Description,
			&i.Color,
			&i.IsDefault,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lookupLabelIDByName = `-- name: LookupLabelIDByName :one
SELECT id
FROM middleman_labels
WHERE repo_id = ?1 AND name = ?2
`

type LookupLabelIDByNameParams struct {
	RepoID int64
	Name   string
}

func (q *Queries) LookupLabelIDByName(ctx context.Context, arg LookupLabelIDByNameParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, lookupLabelIDByName, arg.RepoID, arg.Name)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const lookupLabelIDByPlatformID = `-- name: LookupLabelIDByPlatformID :one
SELECT id
FROM middleman_labels
WHERE repo_id = ?1 AND platform_id = ?2
`

type LookupLabelIDByPlatformIDParams struct {
	RepoID     int64
	PlatformID sql.NullInt64
}

func (q *Queries) LookupLabelIDByPlatformID(ctx context.Context, arg LookupLabelIDByPlatformIDParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, lookupLabelIDByPlatformID, arg.RepoID, arg.PlatformID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const moveIssueLabelAssociations = `-- name: MoveIssueLabelAssociations :exec
INSERT INTO middleman_issue_labels (issue_id, label_id)
SELECT issue_id, ?1
FROM middleman_issue_labels
WHERE middleman_issue_labels.label_id = ?2
ON CONFLICT(issue_id, label_id) DO NOTHING
`

type MoveIssueLabelAssociationsParams struct {
	ToLabelID   int64
	FromLabelID int64
}

func (q *Queries) MoveIssueLabelAssociations(ctx context.Context, arg MoveIssueLabelAssociationsParams) error {
	_, err := q.db.ExecContext(ctx, moveIssueLabelAssociations, arg.ToLabelID, arg.FromLabelID)
	return err
}

const moveMergeRequestLabelAssociations = `-- name: MoveMergeRequestLabelAssociations :exec
INSERT INTO middleman_merge_request_labels (merge_request_id, label_id)
SELECT merge_request_id, ?1
FROM middleman_merge_request_labels
WHERE middleman_merge_request_labels.label_id = ?2
ON CONFLICT(merge_request_id, label_id) DO NOTHING
`

type MoveMergeRequestLabelAssociationsParams struct {
	ToLabelID   int64
	FromLabelID int64
}

func (q *Queries) MoveMergeRequestLabelAssociations(ctx context.Context, arg MoveMergeRequestLabelAssociationsParams) error {
	_, err := q.db.ExecContext(ctx, moveMergeRequestLabelAssociations, arg.ToLabelID, arg.FromLabelID)
	return err
}

const updateLabel = `-- name: UpdateLabel :exec
UPDATE middleman_labels
SET platform_id = COALESCE(NULLIF(?1, 0), platform_id),
    name = ?2,
    description = ?3,
    color = ?4,
    is_default = ?5,
    updated_at = ?6
WHERE id = ?7
`

type UpdateLabelParams struct {
	PlatformID  interface{}
	Name        string
	Description string
	Color       string
	IsDefault   int64
	UpdatedAt   time.Time
	ID          int64
}

func (q *Queries) UpdateLabel(ctx context.Context, arg UpdateLabelParams) error {
	_, err := q.db.ExecContext(ctx, updateLabel,
		arg.PlatformID,
		arg.Name,
		arg.Description,
		arg.Color,
		arg.IsDefault,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
