// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql"
	"time"
)

type MiddlemanKanbanState struct {
	MergeRequestID int64
	Status         string
	UpdatedAt      time.Time
}

type MiddlemanMrWorktreeLink struct {
	ID             int64
	MergeRequestID int64
	WorktreeKey    string
	WorktreePath   sql.NullString
	WorktreeBranch sql.NullString
	LinkedAt       string
}

type MiddlemanRateLimit struct {
	ID            int64
	PlatformHost  string
	ApiType       string
	RequestsHour  int64
	HourStart     time.Time
	RateRemaining int64
	RateLimit     int64
	RateResetAt   sql.NullTime
	UpdatedAt     time.Time
}

type MiddlemanWorkspaceSetupEvent struct {
	ID          int64
	WorkspaceID string
	Stage       string
	Outcome     string
	Message     string
	CreatedAt   time.Time
}

type MiddlemanWorkspaceTmuxSession struct {
	WorkspaceID string
	SessionName string
	TargetKey   string
	CreatedAt   time.Time
}
