// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pr_events.sql

package sqlc

import (
	"context"
	"database/sql"
	"strings"
	"time"
)

const deleteAllMRCommentEvents = `-- name: DeleteAllMRCommentEvents :exec
DELETE FROM middleman_mr_events
WHERE merge_request_id = ?1
  AND event_type = 'issue_comment'
`

func (q *Queries) DeleteAllMRCommentEvents(ctx context.Context, mergeRequestID int64) error {
	_, err := q.db.ExecContext(ctx, deleteAllMRCommentEvents, mergeRequestID)
	return err
}

const deleteMissingMRCommentEvents = `-- name: DeleteMissingMRCommentEvents :exec
DELETE FROM middleman_mr_events
WHERE merge_request_id = ?1
  AND event_type = 'issue_comment'
  AND dedupe_key NOT IN (/*SLICE:dedupe_keys*/?)
`

type DeleteMissingMRCommentEventsParams struct {
	MergeRequestID int64
	DedupeKeys     []string
}

func (q *Queries) DeleteMissingMRCommentEvents(ctx context.Context, arg DeleteMissingMRCommentEventsParams) error {
	query := deleteMissingMRCommentEvents
	var queryParams []interface{}
	queryParams = append(queryParams, arg.MergeRequestID)
	if len(arg.DedupeKeys) > 0 {
		for _, v := range arg.DedupeKeys {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:dedupe_keys*/?", strings.Repeat(",?", len(arg.DedupeKeys))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:dedupe_keys*/?", "NULL", 1)
	}
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}

const getMRLatestNonCommentEventTime = `-- name: GetMRLatestNonCommentEventTime :one
SELECT COALESCE(CAST(MAX(created_at) AS TEXT), '') AS created_at
FROM middleman_mr_events
WHERE merge_request_id = ?1
  AND event_type != 'issue_comment'
`

func (q *Queries) GetMRLatestNonCommentEventTime(ctx context.Context, mergeRequestID int64) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getMRLatestNonCommentEventTime, mergeRequestID)
	var created_at interface{}
	err := row.Scan(&created_at)
	return created_at, err
}

const listMREvents = `-- name: ListMREvents :many
SELECT id, merge_request_id, platform_id, event_type, author, summary, body,
       metadata_json, CAST(created_at AS TEXT) AS created_at, dedupe_key
FROM middleman_mr_events
WHERE merge_request_id = ?1
ORDER BY created_at DESC
`

type ListMREventsRow struct {
	ID             int64
	MergeRequestID int64
	PlatformID     sql.NullInt64
	EventType      string
	Author         string
	Summary        string
	Body           string
	MetadataJson   string
	CreatedAt      string
	DedupeKey      string
}

func (q *Queries) ListMREvents(ctx context.Context, mergeRequestID int64) ([]ListMREventsRow, error) {
	rows, err := q.db.QueryContext(ctx, listMREvents, mergeRequestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMREventsRow
	for rows.Next() {
		var i ListMREventsRow
		if err := rows.Scan(
			&i.ID,
			&i.MergeRequestID,
			&i.PlatformID,
			&i.EventType,
			&i.Author,
			&i.Summary,
			&i.Body,
			&i.MetadataJson,
			&i.CreatedAt,
			&i.DedupeKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const mRCommentEventExists = `-- name: MRCommentEventExists :one
SELECT EXISTS (
    SELECT 1
    FROM middleman_mr_events
    WHERE merge_request_id = ?1
      AND platform_id = ?2
      AND event_type = 'issue_comment'
)
`

type MRCommentEventExistsParams struct {
	MergeRequestID int64
	PlatformID     sql.NullInt64
}

func (q *Queries) MRCommentEventExists(ctx context.Context, arg MRCommentEventExistsParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, mRCommentEventExists, arg.MergeRequestID, arg.PlatformID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const upsertMREvent = `-- name: UpsertMREvent :exec
INSERT INTO middleman_mr_events (
    merge_request_id, platform_id, event_type, author, summary, body,
    metadata_json, created_at, dedupe_key
)
VALUES (
    ?1, ?2, ?3,
    ?4, ?5, ?6, ?7,
    ?8, ?9
)
ON CONFLICT(merge_request_id, dedupe_key) DO UPDATE SET
    platform_id   = excluded.platform_id,
    event_type    = excluded.event_type,
    author        = excluded.author,
    summary       = excluded.summary,
    body          = excluded.body,
    metadata_json = excluded.metadata_json,
    created_at    = excluded.created_at
`

type UpsertMREventParams struct {
	MergeRequestID int64
	PlatformID     sql.NullInt64
	EventType      string
	Author         string
	Summary        string
	Body           string
	MetadataJson   string
	CreatedAt      time.Time
	DedupeKey      string
}

func (q *Queries) UpsertMREvent(ctx context.Context, arg UpsertMREventParams) error {
	_, err := q.db.ExecContext(ctx, upsertMREvent,
		arg.MergeRequestID,
		arg.PlatformID,
		arg.EventType,
		arg.Author,
		arg.Summary,
		arg.Body,
		arg.MetadataJson,
		arg.CreatedAt,
		arg.DedupeKey,
	)
	return err
}
