// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pulls.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const clearMRCI = `-- name: ClearMRCI :exec
UPDATE middleman_merge_requests
SET ci_status = '', ci_checks_json = '', ci_had_pending = 0
WHERE repo_id = ?1 AND number = ?2
`

type ClearMRCIParams struct {
	RepoID int64
	Number int64
}

func (q *Queries) ClearMRCI(ctx context.Context, arg ClearMRCIParams) error {
	_, err := q.db.ExecContext(ctx, clearMRCI, arg.RepoID, arg.Number)
	return err
}

const getDiffSHAs = `-- name: GetDiffSHAs :one
SELECT p.platform_head_sha, p.platform_base_sha,
       p.diff_head_sha, p.diff_base_sha, p.merge_base_sha,
       p.state
FROM middleman_merge_requests p
JOIN middleman_repos r ON r.id = p.repo_id
WHERE r.owner = ?1 AND r.name = ?2 AND p.number = ?3
`

type GetDiffSHAsParams struct {
	Owner  string
	Name   string
	Number int64
}

type GetDiffSHAsRow struct {
	PlatformHeadSha string
	PlatformBaseSha string
	DiffHeadSha     string
	DiffBaseSha     string
	MergeBaseSha    string
	State           string
}

func (q *Queries) GetDiffSHAs(ctx context.Context, arg GetDiffSHAsParams) (GetDiffSHAsRow, error) {
	row := q.db.QueryRowContext(ctx, getDiffSHAs, arg.Owner, arg.Name, arg.Number)
	var i GetDiffSHAsRow
	err := row.Scan(
		&i.PlatformHeadSha,
		&i.PlatformBaseSha,
		&i.DiffHeadSha,
		&i.DiffBaseSha,
		&i.MergeBaseSha,
		&i.State,
	)
	return i, err
}

const getMRIDByOwnerNameNumber = `-- name: GetMRIDByOwnerNameNumber :one
SELECT p.id
FROM middleman_merge_requests p
JOIN middleman_repos r ON r.id = p.repo_id
WHERE r.owner = ?1 AND r.name = ?2 AND p.number = ?3
`

type GetMRIDByOwnerNameNumberParams struct {
	Owner  string
	Name   string
	Number int64
}

func (q *Queries) GetMRIDByOwnerNameNumber(ctx context.Context, arg GetMRIDByOwnerNameNumberParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getMRIDByOwnerNameNumber, arg.Owner, arg.Name, arg.Number)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getMergeRequestByOwnerNameNumber = `-- name: GetMergeRequestByOwnerNameNumber :one
SELECT p.id, p.repo_id, p.platform_id, p.number, p.url, p.title,
       p.author, p.author_display_name, p.state, p.is_draft,
       p.body, p.head_branch, p.base_branch,
       p.platform_head_sha, p.platform_base_sha,
       p.diff_head_sha, p.diff_base_sha, p.merge_base_sha,
       p.head_repo_clone_url,
       p.additions, p.deletions, p.comment_count, p.review_decision,
       p.ci_status, p.ci_checks_json,
       p.created_at, p.updated_at, p.last_activity_at,
       p.merged_at, p.closed_at, p.mergeable_state,
       p.detail_fetched_at, p.ci_had_pending,
       COALESCE(k.status, '') AS kanban_status,
       (s.number IS NOT NULL) AS starred
FROM middleman_merge_requests p
JOIN middleman_repos r ON r.id = p.repo_id
LEFT JOIN middleman_kanban_state k ON k.merge_request_id = p.id
LEFT JOIN middleman_starred_items s
    ON s.item_type = 'pr' AND s.repo_id = p.repo_id AND s.number = p.number
WHERE r.owner = ?1 AND r.name = ?2 AND p.number = ?3
`

type GetMergeRequestByOwnerNameNumberParams struct {
	Owner  string
	Name   string
	Number int64
}

type GetMergeRequestByOwnerNameNumberRow struct {
	ID                int64
	RepoID            int64
	PlatformID        int64
	Number            int64
	Url               string
	Title             string
	Author            string
	AuthorDisplayName string
	State             string
	IsDraft           int64
	Body              string
	HeadBranch        string
	BaseBranch        string
	PlatformHeadSha   string
	PlatformBaseSha   string
	DiffHeadSha       string
	DiffBaseSha       string
	MergeBaseSha      string
	HeadRepoCloneUrl  string
	Additions         int64
	Deletions         int64
	CommentCount      int64
	ReviewDecision    string
	CiStatus          string
	CiChecksJson      string
	CreatedAt         time.Time
	UpdatedAt         time.Time
	LastActivityAt    time.Time
	MergedAt          sql.NullTime
	ClosedAt          sql.NullTime
	MergeableState    string
	DetailFetchedAt   sql.NullTime
	CiHadPending      int64
	KanbanStatus      string
	Starred           interface{}
}

func (q *Queries) GetMergeRequestByOwnerNameNumber(ctx context.Context, arg GetMergeRequestByOwnerNameNumberParams) (GetMergeRequestByOwnerNameNumberRow, error) {
	row := q.db.QueryRowContext(ctx, getMergeRequestByOwnerNameNumber, arg.Owner, arg.Name, arg.Number)
	var i GetMergeRequestByOwnerNameNumberRow
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.PlatformID,
		&i.Number,
		&i.Url,
		&i.Title,
		&i.Author,
		&i.AuthorDisplayName,
		&i.State,
		&i.IsDraft,
		&i.Body,
		&i.HeadBranch,
		&i.BaseBranch,
		&i.PlatformHeadSha,
		&i.PlatformBaseSha,
		&i.DiffHeadSha,
		&i.DiffBaseSha,
		&i.MergeBaseSha,
		&i.HeadRepoCloneUrl,
		&i.Additions,
		&i.Deletions,
		&i.CommentCount,
		&i.ReviewDecision,
		&i.CiStatus,
		&i.CiChecksJson,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastActivityAt,
		&i.MergedAt,
		&i.ClosedAt,
		&i.MergeableState,
		&i.DetailFetchedAt,
		&i.CiHadPending,
		&i.KanbanStatus,
		&i.Starred,
	)
	return i, err
}

const getMergeRequestByRepoIDAndNumber = `-- name: GetMergeRequestByRepoIDAndNumber :one
SELECT p.id, p.repo_id, p.platform_id, p.number, p.url, p.title,
       p.author, p.author_display_name, p.state, p.is_draft,
       p.body, p.head_branch, p.base_branch,
       p.platform_head_sha, p.platform_base_sha,
       p.diff_head_sha, p.diff_base_sha, p.merge_base_sha,
       p.head_repo_clone_url,
       p.additions, p.deletions, p.comment_count, p.review_decision,
       p.ci_status, p.ci_checks_json,
       p.created_at, p.updated_at, p.last_activity_at,
       p.merged_at, p.closed_at, p.mergeable_state,
       p.detail_fetched_at, p.ci_had_pending,
       COALESCE(k.status, '') AS kanban_status,
       (s.number IS NOT NULL) AS starred
FROM middleman_merge_requests p
LEFT JOIN middleman_kanban_state k ON k.merge_request_id = p.id
LEFT JOIN middleman_starred_items s
    ON s.item_type = 'pr' AND s.repo_id = p.repo_id AND s.number = p.number
WHERE p.repo_id = ?1 AND p.number = ?2
`

type GetMergeRequestByRepoIDAndNumberParams struct {
	RepoID int64
	Number int64
}

type GetMergeRequestByRepoIDAndNumberRow struct {
	ID                int64
	RepoID            int64
	PlatformID        int64
	Number            int64
	Url               string
	Title             string
	Author            string
	AuthorDisplayName string
	State             string
	IsDraft           int64
	Body              string
	HeadBranch        string
	BaseBranch        string
	PlatformHeadSha   string
	PlatformBaseSha   string
	DiffHeadSha       string
	DiffBaseSha       string
	MergeBaseSha      string
	HeadRepoCloneUrl  string
	Additions         int64
	Deletions         int64
	CommentCount      int64
	ReviewDecision    string
	CiStatus          string
	CiChecksJson      string
	CreatedAt         time.Time
	UpdatedAt         time.Time
	LastActivityAt    time.Time
	MergedAt          sql.NullTime
	ClosedAt          sql.NullTime
	MergeableState    string
	DetailFetchedAt   sql.NullTime
	CiHadPending      int64
	KanbanStatus      string
	Starred           interface{}
}

func (q *Queries) GetMergeRequestByRepoIDAndNumber(ctx context.Context, arg GetMergeRequestByRepoIDAndNumberParams) (GetMergeRequestByRepoIDAndNumberRow, error) {
	row := q.db.QueryRowContext(ctx, getMergeRequestByRepoIDAndNumber, arg.RepoID, arg.Number)
	var i GetMergeRequestByRepoIDAndNumberRow
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.PlatformID,
		&i.Number,
		&i.Url,
		&i.Title,
		&i.Author,
		&i.AuthorDisplayName,
		&i.State,
		&i.IsDraft,
		&i.Body,
		&i.HeadBranch,
		&i.BaseBranch,
		&i.PlatformHeadSha,
		&i.PlatformBaseSha,
		&i.DiffHeadSha,
		&i.DiffBaseSha,
		&i.MergeBaseSha,
		&i.HeadRepoCloneUrl,
		&i.Additions,
		&i.Deletions,
		&i.CommentCount,
		&i.ReviewDecision,
		&i.CiStatus,
		&i.CiChecksJson,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastActivityAt,
		&i.MergedAt,
		&i.ClosedAt,
		&i.MergeableState,
		&i.DetailFetchedAt,
		&i.CiHadPending,
		&i.KanbanStatus,
		&i.Starred,
	)
	return i, err
}

const getMergeRequestIDByRepoIDAndNumber = `-- name: GetMergeRequestIDByRepoIDAndNumber :one
SELECT id
FROM middleman_merge_requests
WHERE repo_id = ?1 AND number = ?2
`

type GetMergeRequestIDByRepoIDAndNumberParams struct {
	RepoID int64
	Number int64
}

func (q *Queries) GetMergeRequestIDByRepoIDAndNumber(ctx context.Context, arg GetMergeRequestIDByRepoIDAndNumberParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getMergeRequestIDByRepoIDAndNumber, arg.RepoID, arg.Number)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listOpenMRNumbersByRepo = `-- name: ListOpenMRNumbersByRepo :many
SELECT number
FROM middleman_merge_requests
WHERE repo_id = ?1 AND state = 'open'
`

func (q *Queries) ListOpenMRNumbersByRepo(ctx context.Context, repoID int64) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listOpenMRNumbersByRepo, repoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var number int64
		if err := rows.Scan(&number); err != nil {
			return nil, err
		}
		items = append(items, number)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateClosedMRState = `-- name: UpdateClosedMRState :exec
UPDATE middleman_merge_requests
SET state = ?1,
    merged_at = ?2,
    closed_at = ?3,
    updated_at = ?4,
    last_activity_at = ?5,
    platform_head_sha = ?6,
    platform_base_sha = ?7
WHERE repo_id = ?8 AND number = ?9
`

type UpdateClosedMRStateParams struct {
	State           string
	MergedAt        sql.NullTime
	ClosedAt        sql.NullTime
	UpdatedAt       time.Time
	LastActivityAt  time.Time
	PlatformHeadSha string
	PlatformBaseSha string
	RepoID          int64
	Number          int64
}

func (q *Queries) UpdateClosedMRState(ctx context.Context, arg UpdateClosedMRStateParams) error {
	_, err := q.db.ExecContext(ctx, updateClosedMRState,
		arg.State,
		arg.MergedAt,
		arg.ClosedAt,
		arg.UpdatedAt,
		arg.LastActivityAt,
		arg.PlatformHeadSha,
		arg.PlatformBaseSha,
		arg.RepoID,
		arg.Number,
	)
	return err
}

const updateDiffSHAs = `-- name: UpdateDiffSHAs :exec
UPDATE middleman_merge_requests
SET diff_head_sha = ?1,
    diff_base_sha = ?2,
    merge_base_sha = ?3
WHERE repo_id = ?4 AND number = ?5
`

type UpdateDiffSHAsParams struct {
	DiffHeadSha  string
	DiffBaseSha  string
	MergeBaseSha string
	RepoID       int64
	Number       int64
}

func (q *Queries) UpdateDiffSHAs(ctx context.Context, arg UpdateDiffSHAsParams) error {
	_, err := q.db.ExecContext(ctx, updateDiffSHAs,
		arg.DiffHeadSha,
		arg.DiffBaseSha,
		arg.MergeBaseSha,
		arg.RepoID,
		arg.Number,
	)
	return err
}

const updateMRCIStatus = `-- name: UpdateMRCIStatus :exec
UPDATE middleman_merge_requests
SET ci_status = ?1,
    ci_checks_json = ?2
WHERE repo_id = ?3 AND number = ?4
`

type UpdateMRCIStatusParams struct {
	CiStatus     string
	CiChecksJson string
	RepoID       int64
	Number       int64
}

func (q *Queries) UpdateMRCIStatus(ctx context.Context, arg UpdateMRCIStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateMRCIStatus,
		arg.CiStatus,
		arg.CiChecksJson,
		arg.RepoID,
		arg.Number,
	)
	return err
}

const updateMRDerivedFields = `-- name: UpdateMRDerivedFields :exec
UPDATE middleman_merge_requests
SET review_decision = ?1,
    comment_count = ?2,
    last_activity_at = ?3
WHERE repo_id = ?4 AND number = ?5
`

type UpdateMRDerivedFieldsParams struct {
	ReviewDecision string
	CommentCount   int64
	LastActivityAt time.Time
	RepoID         int64
	Number         int64
}

func (q *Queries) UpdateMRDerivedFields(ctx context.Context, arg UpdateMRDerivedFieldsParams) error {
	_, err := q.db.ExecContext(ctx, updateMRDerivedFields,
		arg.ReviewDecision,
		arg.CommentCount,
		arg.LastActivityAt,
		arg.RepoID,
		arg.Number,
	)
	return err
}

const updateMRDetailFetched = `-- name: UpdateMRDetailFetched :exec
UPDATE middleman_merge_requests
SET detail_fetched_at = datetime('now'),
    ci_had_pending = ?1
WHERE repo_id = (
    SELECT id FROM middleman_repos
    WHERE platform_host = ?2
      AND owner = ?3
      AND name = ?4
) AND number = ?5
`

type UpdateMRDetailFetchedParams struct {
	CiHadPending int64
	PlatformHost string
	Owner        string
	Name         string
	Number       int64
}

func (q *Queries) UpdateMRDetailFetched(ctx context.Context, arg UpdateMRDetailFetchedParams) error {
	_, err := q.db.ExecContext(ctx, updateMRDetailFetched,
		arg.CiHadPending,
		arg.PlatformHost,
		arg.Owner,
		arg.Name,
		arg.Number,
	)
	return err
}

const updateMRState = `-- name: UpdateMRState :exec
UPDATE middleman_merge_requests
SET state = ?1,
    merged_at = ?2,
    closed_at = ?3,
    updated_at = ?4,
    last_activity_at = ?5
WHERE repo_id = ?6 AND number = ?7
`

type UpdateMRStateParams struct {
	State          string
	MergedAt       sql.NullTime
	ClosedAt       sql.NullTime
	UpdatedAt      time.Time
	LastActivityAt time.Time
	RepoID         int64
	Number         int64
}

func (q *Queries) UpdateMRState(ctx context.Context, arg UpdateMRStateParams) error {
	_, err := q.db.ExecContext(ctx, updateMRState,
		arg.State,
		arg.MergedAt,
		arg.ClosedAt,
		arg.UpdatedAt,
		arg.LastActivityAt,
		arg.RepoID,
		arg.Number,
	)
	return err
}

const updateMRTitleBody = `-- name: UpdateMRTitleBody :exec
UPDATE middleman_merge_requests
SET title = ?1,
    body = ?2,
    updated_at = ?3,
    last_activity_at = MAX(last_activity_at, ?4)
WHERE id = ?5 AND updated_at <= ?3
`

type UpdateMRTitleBodyParams struct {
	Title          string
	Body           string
	UpdatedAt      time.Time
	LastActivityAt interface{}
	ID             int64
}

func (q *Queries) UpdateMRTitleBody(ctx context.Context, arg UpdateMRTitleBodyParams) error {
	_, err := q.db.ExecContext(ctx, updateMRTitleBody,
		arg.Title,
		arg.Body,
		arg.UpdatedAt,
		arg.LastActivityAt,
		arg.ID,
	)
	return err
}

const updatePlatformSHAs = `-- name: UpdatePlatformSHAs :exec
UPDATE middleman_merge_requests
SET platform_head_sha = ?1,
    platform_base_sha = ?2
WHERE repo_id = ?3 AND number = ?4
`

type UpdatePlatformSHAsParams struct {
	PlatformHeadSha string
	PlatformBaseSha string
	RepoID          int64
	Number          int64
}

func (q *Queries) UpdatePlatformSHAs(ctx context.Context, arg UpdatePlatformSHAsParams) error {
	_, err := q.db.ExecContext(ctx, updatePlatformSHAs,
		arg.PlatformHeadSha,
		arg.PlatformBaseSha,
		arg.RepoID,
		arg.Number,
	)
	return err
}

const upsertMergeRequest = `-- name: UpsertMergeRequest :exec
INSERT INTO middleman_merge_requests (
    repo_id, platform_id, number, url, title, author, author_display_name,
    state, is_draft, body, head_branch, base_branch,
    platform_head_sha, platform_base_sha,
    head_repo_clone_url,
    additions, deletions, comment_count,
    review_decision, ci_status, ci_checks_json,
    detail_fetched_at, ci_had_pending,
    created_at, updated_at,
    last_activity_at, merged_at, closed_at, mergeable_state
)
VALUES (
    ?1, ?2, ?3, ?4,
    ?5, ?6, ?7,
    ?8, ?9, ?10, ?11,
    ?12, ?13, ?14,
    ?15, ?16, ?17,
    ?18, ?19, ?20,
    ?21, ?22, ?23,
    ?24, ?25, ?26,
    ?27, ?28, ?29
)
ON CONFLICT(repo_id, number) DO UPDATE SET
    platform_id          = excluded.platform_id,
    url                  = excluded.url,
    title                = excluded.title,
    author               = excluded.author,
    author_display_name  = excluded.author_display_name,
    state                = excluded.state,
    is_draft             = excluded.is_draft,
    body                 = excluded.body,
    head_branch          = excluded.head_branch,
    base_branch          = excluded.base_branch,
    platform_head_sha    = excluded.platform_head_sha,
    platform_base_sha    = excluded.platform_base_sha,
    head_repo_clone_url  = excluded.head_repo_clone_url,
    additions            = excluded.additions,
    deletions            = excluded.deletions,
    comment_count        = excluded.comment_count,
    review_decision      = excluded.review_decision,
    ci_status            = excluded.ci_status,
    ci_checks_json       = excluded.ci_checks_json,
    detail_fetched_at    = COALESCE(middleman_merge_requests.detail_fetched_at, excluded.detail_fetched_at),
    ci_had_pending       = middleman_merge_requests.ci_had_pending,
    updated_at           = excluded.updated_at,
    last_activity_at     = excluded.last_activity_at,
    merged_at            = excluded.merged_at,
    closed_at            = excluded.closed_at,
    mergeable_state      = excluded.mergeable_state
WHERE excluded.updated_at >= middleman_merge_requests.updated_at
`

type UpsertMergeRequestParams struct {
	RepoID            int64
	PlatformID        int64
	Number            int64
	Url               string
	Title             string
	Author            string
	AuthorDisplayName string
	State             string
	IsDraft           int64
	Body              string
	HeadBranch        string
	BaseBranch        string
	PlatformHeadSha   string
	PlatformBaseSha   string
	HeadRepoCloneUrl  string
	Additions         int64
	Deletions         int64
	CommentCount      int64
	ReviewDecision    string
	CiStatus          string
	CiChecksJson      string
	DetailFetchedAt   sql.NullTime
	CiHadPending      int64
	CreatedAt         time.Time
	UpdatedAt         time.Time
	LastActivityAt    time.Time
	MergedAt          sql.NullTime
	ClosedAt          sql.NullTime
	MergeableState    string
}

func (q *Queries) UpsertMergeRequest(ctx context.Context, arg UpsertMergeRequestParams) error {
	_, err := q.db.ExecContext(ctx, upsertMergeRequest,
		arg.RepoID,
		arg.PlatformID,
		arg.Number,
		arg.Url,
		arg.Title,
		arg.Author,
		arg.AuthorDisplayName,
		arg.State,
		arg.IsDraft,
		arg.Body,
		arg.HeadBranch,
		arg.BaseBranch,
		arg.PlatformHeadSha,
		arg.PlatformBaseSha,
		arg.HeadRepoCloneUrl,
		arg.Additions,
		arg.Deletions,
		arg.CommentCount,
		arg.ReviewDecision,
		arg.CiStatus,
		arg.CiChecksJson,
		arg.DetailFetchedAt,
		arg.CiHadPending,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.LastActivityAt,
		arg.MergedAt,
		arg.ClosedAt,
		arg.MergeableState,
	)
	return err
}
