// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rate_limits.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const getRateLimit = `-- name: GetRateLimit :one
SELECT id, platform_host, api_type, requests_hour, hour_start,
       rate_remaining, rate_limit, rate_reset_at, updated_at
FROM middleman_rate_limits
WHERE platform_host = ?1
  AND api_type = ?2
`

type GetRateLimitParams struct {
	PlatformHost string
	ApiType      string
}

func (q *Queries) GetRateLimit(ctx context.Context, arg GetRateLimitParams) (MiddlemanRateLimit, error) {
	row := q.db.QueryRowContext(ctx, getRateLimit, arg.PlatformHost, arg.ApiType)
	var i MiddlemanRateLimit
	err := row.Scan(
		&i.ID,
		&i.PlatformHost,
		&i.ApiType,
		&i.RequestsHour,
		&i.HourStart,
		&i.RateRemaining,
		&i.RateLimit,
		&i.RateResetAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertRateLimit = `-- name: UpsertRateLimit :exec
INSERT INTO middleman_rate_limits (
    platform_host, api_type, requests_hour, hour_start,
    rate_remaining, rate_limit, rate_reset_at, updated_at
)
VALUES (
    ?1, ?2, ?3,
    ?4, ?5, ?6,
    ?7, datetime('now')
)
ON CONFLICT(platform_host, api_type) DO UPDATE SET
    requests_hour  = excluded.requests_hour,
    hour_start     = excluded.hour_start,
    rate_remaining = excluded.rate_remaining,
    rate_limit     = excluded.rate_limit,
    rate_reset_at  = excluded.rate_reset_at,
    updated_at     = datetime('now')
`

type UpsertRateLimitParams struct {
	PlatformHost  string
	ApiType       string
	RequestsHour  int64
	HourStart     time.Time
	RateRemaining int64
	RateLimit     int64
	RateResetAt   sql.NullTime
}

func (q *Queries) UpsertRateLimit(ctx context.Context, arg UpsertRateLimitParams) error {
	_, err := q.db.ExecContext(ctx, upsertRateLimit,
		arg.PlatformHost,
		arg.ApiType,
		arg.RequestsHour,
		arg.HourStart,
		arg.RateRemaining,
		arg.RateLimit,
		arg.RateResetAt,
	)
	return err
}
