// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: repos.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const getRepoByHostOwnerName = `-- name: GetRepoByHostOwnerName :one
SELECT id, platform, platform_host, owner, name,
       last_sync_started_at, last_sync_completed_at,
       last_sync_error, allow_squash_merge, allow_merge_commit,
       allow_rebase_merge,
       backfill_pr_page, backfill_pr_complete,
       backfill_pr_completed_at,
       backfill_issue_page, backfill_issue_complete,
       backfill_issue_completed_at,
       created_at
FROM middleman_repos
WHERE platform_host = ? AND owner = ? AND name = ?
`

type GetRepoByHostOwnerNameParams struct {
	PlatformHost string
	Owner        string
	Name         string
}

type GetRepoByHostOwnerNameRow struct {
	ID                       int64
	Platform                 string
	PlatformHost             string
	Owner                    string
	Name                     string
	LastSyncStartedAt        sql.NullTime
	LastSyncCompletedAt      sql.NullTime
	LastSyncError            sql.NullString
	AllowSquashMerge         int64
	AllowMergeCommit         int64
	AllowRebaseMerge         int64
	BackfillPrPage           int64
	BackfillPrComplete       int64
	BackfillPrCompletedAt    sql.NullTime
	BackfillIssuePage        int64
	BackfillIssueComplete    int64
	BackfillIssueCompletedAt sql.NullTime
	CreatedAt                time.Time
}

func (q *Queries) GetRepoByHostOwnerName(ctx context.Context, arg GetRepoByHostOwnerNameParams) (GetRepoByHostOwnerNameRow, error) {
	row := q.db.QueryRowContext(ctx, getRepoByHostOwnerName, arg.PlatformHost, arg.Owner, arg.Name)
	var i GetRepoByHostOwnerNameRow
	err := row.Scan(
		&i.ID,
		&i.Platform,
		&i.PlatformHost,
		&i.Owner,
		&i.Name,
		&i.LastSyncStartedAt,
		&i.LastSyncCompletedAt,
		&i.LastSyncError,
		&i.AllowSquashMerge,
		&i.AllowMergeCommit,
		&i.AllowRebaseMerge,
		&i.BackfillPrPage,
		&i.BackfillPrComplete,
		&i.BackfillPrCompletedAt,
		&i.BackfillIssuePage,
		&i.BackfillIssueComplete,
		&i.BackfillIssueCompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getRepoByID = `-- name: GetRepoByID :one
SELECT id, platform, platform_host, owner, name,
       last_sync_started_at, last_sync_completed_at,
       last_sync_error, allow_squash_merge, allow_merge_commit,
       allow_rebase_merge,
       backfill_pr_page, backfill_pr_complete,
       backfill_pr_completed_at,
       backfill_issue_page, backfill_issue_complete,
       backfill_issue_completed_at,
       created_at
FROM middleman_repos
WHERE id = ?
`

type GetRepoByIDRow struct {
	ID                       int64
	Platform                 string
	PlatformHost             string
	Owner                    string
	Name                     string
	LastSyncStartedAt        sql.NullTime
	LastSyncCompletedAt      sql.NullTime
	LastSyncError            sql.NullString
	AllowSquashMerge         int64
	AllowMergeCommit         int64
	AllowRebaseMerge         int64
	BackfillPrPage           int64
	BackfillPrComplete       int64
	BackfillPrCompletedAt    sql.NullTime
	BackfillIssuePage        int64
	BackfillIssueComplete    int64
	BackfillIssueCompletedAt sql.NullTime
	CreatedAt                time.Time
}

func (q *Queries) GetRepoByID(ctx context.Context, id int64) (GetRepoByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getRepoByID, id)
	var i GetRepoByIDRow
	err := row.Scan(
		&i.ID,
		&i.Platform,
		&i.PlatformHost,
		&i.Owner,
		&i.Name,
		&i.LastSyncStartedAt,
		&i.LastSyncCompletedAt,
		&i.LastSyncError,
		&i.AllowSquashMerge,
		&i.AllowMergeCommit,
		&i.AllowRebaseMerge,
		&i.BackfillPrPage,
		&i.BackfillPrComplete,
		&i.BackfillPrCompletedAt,
		&i.BackfillIssuePage,
		&i.BackfillIssueComplete,
		&i.BackfillIssueCompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getRepoByOwnerName = `-- name: GetRepoByOwnerName :one
SELECT id, platform, platform_host, owner, name,
       last_sync_started_at, last_sync_completed_at,
       last_sync_error, allow_squash_merge, allow_merge_commit,
       allow_rebase_merge,
       backfill_pr_page, backfill_pr_complete,
       backfill_pr_completed_at,
       backfill_issue_page, backfill_issue_complete,
       backfill_issue_completed_at,
       created_at
FROM middleman_repos
WHERE owner = ? AND name = ?
ORDER BY platform_host ASC
LIMIT 1
`

type GetRepoByOwnerNameParams struct {
	Owner string
	Name  string
}

type GetRepoByOwnerNameRow struct {
	ID                       int64
	Platform                 string
	PlatformHost             string
	Owner                    string
	Name                     string
	LastSyncStartedAt        sql.NullTime
	LastSyncCompletedAt      sql.NullTime
	LastSyncError            sql.NullString
	AllowSquashMerge         int64
	AllowMergeCommit         int64
	AllowRebaseMerge         int64
	BackfillPrPage           int64
	BackfillPrComplete       int64
	BackfillPrCompletedAt    sql.NullTime
	BackfillIssuePage        int64
	BackfillIssueComplete    int64
	BackfillIssueCompletedAt sql.NullTime
	CreatedAt                time.Time
}

func (q *Queries) GetRepoByOwnerName(ctx context.Context, arg GetRepoByOwnerNameParams) (GetRepoByOwnerNameRow, error) {
	row := q.db.QueryRowContext(ctx, getRepoByOwnerName, arg.Owner, arg.Name)
	var i GetRepoByOwnerNameRow
	err := row.Scan(
		&i.ID,
		&i.Platform,
		&i.PlatformHost,
		&i.Owner,
		&i.Name,
		&i.LastSyncStartedAt,
		&i.LastSyncCompletedAt,
		&i.LastSyncError,
		&i.AllowSquashMerge,
		&i.AllowMergeCommit,
		&i.AllowRebaseMerge,
		&i.BackfillPrPage,
		&i.BackfillPrComplete,
		&i.BackfillPrCompletedAt,
		&i.BackfillIssuePage,
		&i.BackfillIssueComplete,
		&i.BackfillIssueCompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listRepos = `-- name: ListRepos :many
SELECT id, platform, platform_host, owner, name,
       last_sync_started_at, last_sync_completed_at,
       last_sync_error, allow_squash_merge, allow_merge_commit,
       allow_rebase_merge,
       backfill_pr_page, backfill_pr_complete,
       backfill_pr_completed_at,
       backfill_issue_page, backfill_issue_complete,
       backfill_issue_completed_at,
       created_at
FROM middleman_repos
ORDER BY owner, name
`

type ListReposRow struct {
	ID                       int64
	Platform                 string
	PlatformHost             string
	Owner                    string
	Name                     string
	LastSyncStartedAt        sql.NullTime
	LastSyncCompletedAt      sql.NullTime
	LastSyncError            sql.NullString
	AllowSquashMerge         int64
	AllowMergeCommit         int64
	AllowRebaseMerge         int64
	BackfillPrPage           int64
	BackfillPrComplete       int64
	BackfillPrCompletedAt    sql.NullTime
	BackfillIssuePage        int64
	BackfillIssueComplete    int64
	BackfillIssueCompletedAt sql.NullTime
	CreatedAt                time.Time
}

func (q *Queries) ListRepos(ctx context.Context) ([]ListReposRow, error) {
	rows, err := q.db.QueryContext(ctx, listRepos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReposRow
	for rows.Next() {
		var i ListReposRow
		if err := rows.Scan(
			&i.ID,
			&i.Platform,
			&i.PlatformHost,
			&i.Owner,
			&i.Name,
			&i.LastSyncStartedAt,
			&i.LastSyncCompletedAt,
			&i.LastSyncError,
			&i.AllowSquashMerge,
			&i.AllowMergeCommit,
			&i.AllowRebaseMerge,
			&i.BackfillPrPage,
			&i.BackfillPrComplete,
			&i.BackfillPrCompletedAt,
			&i.BackfillIssuePage,
			&i.BackfillIssueComplete,
			&i.BackfillIssueCompletedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purgeOtherHostIssueEvents = `-- name: PurgeOtherHostIssueEvents :exec
DELETE FROM middleman_issue_events
WHERE issue_id IN (
    SELECT id FROM middleman_issues
    WHERE repo_id IN (
        SELECT id FROM middleman_repos WHERE platform_host != ?
    )
)
`

func (q *Queries) PurgeOtherHostIssueEvents(ctx context.Context, platformHost string) error {
	_, err := q.db.ExecContext(ctx, purgeOtherHostIssueEvents, platformHost)
	return err
}

const purgeOtherHostIssues = `-- name: PurgeOtherHostIssues :exec
DELETE FROM middleman_issues
WHERE repo_id IN (
    SELECT id FROM middleman_repos WHERE platform_host != ?
)
`

func (q *Queries) PurgeOtherHostIssues(ctx context.Context, platformHost string) error {
	_, err := q.db.ExecContext(ctx, purgeOtherHostIssues, platformHost)
	return err
}

const purgeOtherHostKanbanState = `-- name: PurgeOtherHostKanbanState :exec
DELETE FROM middleman_kanban_state
WHERE merge_request_id IN (
    SELECT id FROM middleman_merge_requests
    WHERE repo_id IN (
        SELECT id FROM middleman_repos WHERE platform_host != ?
    )
)
`

func (q *Queries) PurgeOtherHostKanbanState(ctx context.Context, platformHost string) error {
	_, err := q.db.ExecContext(ctx, purgeOtherHostKanbanState, platformHost)
	return err
}

const purgeOtherHostMergeRequestEvents = `-- name: PurgeOtherHostMergeRequestEvents :exec
DELETE FROM middleman_mr_events
WHERE merge_request_id IN (
    SELECT id FROM middleman_merge_requests
    WHERE repo_id IN (
        SELECT id FROM middleman_repos WHERE platform_host != ?
    )
)
`

func (q *Queries) PurgeOtherHostMergeRequestEvents(ctx context.Context, platformHost string) error {
	_, err := q.db.ExecContext(ctx, purgeOtherHostMergeRequestEvents, platformHost)
	return err
}

const purgeOtherHostMergeRequests = `-- name: PurgeOtherHostMergeRequests :exec
DELETE FROM middleman_merge_requests
WHERE repo_id IN (
    SELECT id FROM middleman_repos WHERE platform_host != ?
)
`

func (q *Queries) PurgeOtherHostMergeRequests(ctx context.Context, platformHost string) error {
	_, err := q.db.ExecContext(ctx, purgeOtherHostMergeRequests, platformHost)
	return err
}

const purgeOtherHostRateLimits = `-- name: PurgeOtherHostRateLimits :exec
DELETE FROM middleman_rate_limits
WHERE platform_host != ?
`

func (q *Queries) PurgeOtherHostRateLimits(ctx context.Context, platformHost string) error {
	_, err := q.db.ExecContext(ctx, purgeOtherHostRateLimits, platformHost)
	return err
}

const purgeOtherHostRepos = `-- name: PurgeOtherHostRepos :exec
DELETE FROM middleman_repos
WHERE platform_host != ?
`

func (q *Queries) PurgeOtherHostRepos(ctx context.Context, platformHost string) error {
	_, err := q.db.ExecContext(ctx, purgeOtherHostRepos, platformHost)
	return err
}

const purgeOtherHostStarredItems = `-- name: PurgeOtherHostStarredItems :exec
DELETE FROM middleman_starred_items
WHERE repo_id IN (
    SELECT id FROM middleman_repos WHERE platform_host != ?
)
`

func (q *Queries) PurgeOtherHostStarredItems(ctx context.Context, platformHost string) error {
	_, err := q.db.ExecContext(ctx, purgeOtherHostStarredItems, platformHost)
	return err
}

const purgeOtherHostWorktreeLinks = `-- name: PurgeOtherHostWorktreeLinks :exec
DELETE FROM middleman_mr_worktree_links
WHERE merge_request_id IN (
    SELECT id FROM middleman_merge_requests
    WHERE repo_id IN (
        SELECT id FROM middleman_repos WHERE platform_host != ?
    )
)
`

func (q *Queries) PurgeOtherHostWorktreeLinks(ctx context.Context, platformHost string) error {
	_, err := q.db.ExecContext(ctx, purgeOtherHostWorktreeLinks, platformHost)
	return err
}

const updateBackfillCursor = `-- name: UpdateBackfillCursor :exec
UPDATE middleman_repos
SET backfill_pr_page = ?,
    backfill_pr_complete = ?,
    backfill_pr_completed_at = ?,
    backfill_issue_page = ?,
    backfill_issue_complete = ?,
    backfill_issue_completed_at = ?
WHERE id = ?
`

type UpdateBackfillCursorParams struct {
	BackfillPrPage           int64
	BackfillPrComplete       int64
	BackfillPrCompletedAt    sql.NullTime
	BackfillIssuePage        int64
	BackfillIssueComplete    int64
	BackfillIssueCompletedAt sql.NullTime
	ID                       int64
}

func (q *Queries) UpdateBackfillCursor(ctx context.Context, arg UpdateBackfillCursorParams) error {
	_, err := q.db.ExecContext(ctx, updateBackfillCursor,
		arg.BackfillPrPage,
		arg.BackfillPrComplete,
		arg.BackfillPrCompletedAt,
		arg.BackfillIssuePage,
		arg.BackfillIssueComplete,
		arg.BackfillIssueCompletedAt,
		arg.ID,
	)
	return err
}

const updateRepoSettings = `-- name: UpdateRepoSettings :exec
UPDATE middleman_repos
SET allow_squash_merge = ?,
    allow_merge_commit = ?,
    allow_rebase_merge = ?
WHERE id = ?
`

type UpdateRepoSettingsParams struct {
	AllowSquashMerge int64
	AllowMergeCommit int64
	AllowRebaseMerge int64
	ID               int64
}

func (q *Queries) UpdateRepoSettings(ctx context.Context, arg UpdateRepoSettingsParams) error {
	_, err := q.db.ExecContext(ctx, updateRepoSettings,
		arg.AllowSquashMerge,
		arg.AllowMergeCommit,
		arg.AllowRebaseMerge,
		arg.ID,
	)
	return err
}

const updateRepoSyncCompleted = `-- name: UpdateRepoSyncCompleted :exec
UPDATE middleman_repos
SET last_sync_completed_at = ?, last_sync_error = ?
WHERE id = ?
`

type UpdateRepoSyncCompletedParams struct {
	LastSyncCompletedAt sql.NullTime
	LastSyncError       sql.NullString
	ID                  int64
}

func (q *Queries) UpdateRepoSyncCompleted(ctx context.Context, arg UpdateRepoSyncCompletedParams) error {
	_, err := q.db.ExecContext(ctx, updateRepoSyncCompleted, arg.LastSyncCompletedAt, arg.LastSyncError, arg.ID)
	return err
}

const updateRepoSyncStarted = `-- name: UpdateRepoSyncStarted :exec
UPDATE middleman_repos
SET last_sync_started_at = ?
WHERE id = ?
`

type UpdateRepoSyncStartedParams struct {
	LastSyncStartedAt sql.NullTime
	ID                int64
}

func (q *Queries) UpdateRepoSyncStarted(ctx context.Context, arg UpdateRepoSyncStartedParams) error {
	_, err := q.db.ExecContext(ctx, updateRepoSyncStarted, arg.LastSyncStartedAt, arg.ID)
	return err
}

const upsertRepo = `-- name: UpsertRepo :one
INSERT INTO middleman_repos (platform, platform_host, owner, name)
VALUES ('github', ?, ?, ?)
ON CONFLICT(platform, platform_host, owner, name) DO UPDATE SET
    platform = excluded.platform
RETURNING id
`

type UpsertRepoParams struct {
	PlatformHost string
	Owner        string
	Name         string
}

func (q *Queries) UpsertRepo(ctx context.Context, arg UpsertRepoParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, upsertRepo, arg.PlatformHost, arg.Owner, arg.Name)
	var id int64
	err := row.Scan(&id)
	return id, err
}
