// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: repo_summaries.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const listRepoSummaryAuthors = `-- name: ListRepoSummaryAuthors :many
WITH author_items AS (
    SELECT repo_id, author, last_activity_at
    FROM middleman_merge_requests
    WHERE author <> ''
    UNION ALL
    SELECT repo_id, author, last_activity_at
    FROM middleman_issues
    WHERE author <> ''
),
author_totals AS (
    SELECT repo_id,
           author,
           COUNT(*) AS item_count,
           MAX(last_activity_at) AS most_recent_activity_at
    FROM author_items
    GROUP BY repo_id, author
),
ranked AS (
    SELECT repo_id,
           author,
           item_count,
           ROW_NUMBER() OVER (
               PARTITION BY repo_id
               ORDER BY item_count DESC, most_recent_activity_at DESC, author ASC
           ) AS row_num
    FROM author_totals
)
SELECT repo_id, author, item_count
FROM ranked
WHERE row_num <= 3
ORDER BY repo_id, row_num
`

type ListRepoSummaryAuthorsRow struct {
	RepoID    int64
	Author    string
	ItemCount int64
}

func (q *Queries) ListRepoSummaryAuthors(ctx context.Context) ([]ListRepoSummaryAuthorsRow, error) {
	rows, err := q.db.QueryContext(ctx, listRepoSummaryAuthors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRepoSummaryAuthorsRow
	for rows.Next() {
		var i ListRepoSummaryAuthorsRow
		if err := rows.Scan(&i.RepoID, &i.Author, &i.ItemCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRepoSummaryIssues = `-- name: ListRepoSummaryIssues :many
WITH ranked AS (
    SELECT repo_id,
           number,
           title,
           author,
           state,
           url,
           last_activity_at,
           ROW_NUMBER() OVER (
               PARTITION BY repo_id
               ORDER BY last_activity_at DESC, number DESC
           ) AS row_num
    FROM middleman_issues
    WHERE state = 'open'
)
SELECT repo_id, number, title, author, state, url,
       CAST(last_activity_at AS TEXT) AS last_activity_at
FROM ranked
WHERE row_num <= 3
ORDER BY repo_id, row_num
`

type ListRepoSummaryIssuesRow struct {
	RepoID         int64
	Number         int64
	Title          string
	Author         string
	State          string
	Url            string
	LastActivityAt string
}

func (q *Queries) ListRepoSummaryIssues(ctx context.Context) ([]ListRepoSummaryIssuesRow, error) {
	rows, err := q.db.QueryContext(ctx, listRepoSummaryIssues)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRepoSummaryIssuesRow
	for rows.Next() {
		var i ListRepoSummaryIssuesRow
		if err := rows.Scan(
			&i.RepoID,
			&i.Number,
			&i.Title,
			&i.Author,
			&i.State,
			&i.Url,
			&i.LastActivityAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRepoSummaryOverviews = `-- name: ListRepoSummaryOverviews :many
SELECT repo_id,
       latest_release_tag,
       latest_release_name,
       latest_release_url,
       latest_release_target,
       latest_release_prerelease,
       COALESCE(CAST(latest_release_published_at AS TEXT), '') AS latest_release_published_at,
       commits_since_release,
       commit_timeline_json,
       releases_json,
       COALESCE(CAST(timeline_updated_at AS TEXT), '') AS timeline_updated_at
FROM middleman_repo_overviews
`

type ListRepoSummaryOverviewsRow struct {
	RepoID                   int64
	LatestReleaseTag         string
	LatestReleaseName        string
	LatestReleaseUrl         string
	LatestReleaseTarget      string
	LatestReleasePrerelease  int64
	LatestReleasePublishedAt interface{}
	CommitsSinceRelease      sql.NullInt64
	CommitTimelineJson       string
	ReleasesJson             string
	TimelineUpdatedAt        interface{}
}

func (q *Queries) ListRepoSummaryOverviews(ctx context.Context) ([]ListRepoSummaryOverviewsRow, error) {
	rows, err := q.db.QueryContext(ctx, listRepoSummaryOverviews)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRepoSummaryOverviewsRow
	for rows.Next() {
		var i ListRepoSummaryOverviewsRow
		if err := rows.Scan(
			&i.RepoID,
			&i.LatestReleaseTag,
			&i.LatestReleaseName,
			&i.LatestReleaseUrl,
			&i.LatestReleaseTarget,
			&i.LatestReleasePrerelease,
			&i.LatestReleasePublishedAt,
			&i.CommitsSinceRelease,
			&i.CommitTimelineJson,
			&i.ReleasesJson,
			&i.TimelineUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRepoSummaryStats = `-- name: ListRepoSummaryStats :many
WITH pr_stats AS (
    SELECT repo_id,
           COUNT(*) AS cached_pr_count,
           SUM(CASE WHEN state = 'open' THEN 1 ELSE 0 END) AS open_pr_count,
           SUM(CASE WHEN state = 'open' AND is_draft THEN 1 ELSE 0 END) AS draft_pr_count,
           MAX(last_activity_at) AS last_pr_activity_at
    FROM middleman_merge_requests
    GROUP BY repo_id
),
issue_stats AS (
    SELECT repo_id,
           COUNT(*) AS cached_issue_count,
           SUM(CASE WHEN state = 'open' THEN 1 ELSE 0 END) AS open_issue_count,
           MAX(last_activity_at) AS last_issue_activity_at
    FROM middleman_issues
    GROUP BY repo_id
)
SELECT r.id,
       COALESCE(pr.cached_pr_count, 0) AS cached_pr_count,
       COALESCE(pr.open_pr_count, 0) AS open_pr_count,
       COALESCE(pr.draft_pr_count, 0) AS draft_pr_count,
       COALESCE(i.cached_issue_count, 0) AS cached_issue_count,
       COALESCE(i.open_issue_count, 0) AS open_issue_count,
       COALESCE(CAST(
           CASE
               WHEN pr.last_pr_activity_at IS NULL THEN i.last_issue_activity_at
               WHEN i.last_issue_activity_at IS NULL THEN pr.last_pr_activity_at
               WHEN pr.last_pr_activity_at >= i.last_issue_activity_at THEN pr.last_pr_activity_at
               ELSE i.last_issue_activity_at
           END AS TEXT
       ), '') AS most_recent_activity_at
FROM middleman_repos r
LEFT JOIN pr_stats pr ON pr.repo_id = r.id
LEFT JOIN issue_stats i ON i.repo_id = r.id
ORDER BY r.owner, r.name
`

type ListRepoSummaryStatsRow struct {
	ID                   int64
	CachedPrCount        int64
	OpenPrCount          float64
	DraftPrCount         float64
	CachedIssueCount     int64
	OpenIssueCount       float64
	MostRecentActivityAt interface{}
}

func (q *Queries) ListRepoSummaryStats(ctx context.Context) ([]ListRepoSummaryStatsRow, error) {
	rows, err := q.db.QueryContext(ctx, listRepoSummaryStats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRepoSummaryStatsRow
	for rows.Next() {
		var i ListRepoSummaryStatsRow
		if err := rows.Scan(
			&i.ID,
			&i.CachedPrCount,
			&i.OpenPrCount,
			&i.DraftPrCount,
			&i.CachedIssueCount,
			&i.OpenIssueCount,
			&i.MostRecentActivityAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertRepoOverview = `-- name: UpsertRepoOverview :exec
INSERT INTO middleman_repo_overviews (
    repo_id, latest_release_tag, latest_release_name,
    latest_release_url, latest_release_target,
    latest_release_prerelease, latest_release_published_at,
    commits_since_release, commit_timeline_json,
    releases_json, timeline_updated_at, updated_at
)
VALUES (
    ?1, ?2, ?3,
    ?4, ?5,
    ?6, ?7,
    ?8, ?9,
    ?10, ?11, ?12
)
ON CONFLICT(repo_id) DO UPDATE SET
    latest_release_tag = excluded.latest_release_tag,
    latest_release_name = excluded.latest_release_name,
    latest_release_url = excluded.latest_release_url,
    latest_release_target = excluded.latest_release_target,
    latest_release_prerelease = excluded.latest_release_prerelease,
    latest_release_published_at = excluded.latest_release_published_at,
    commits_since_release = CASE
        WHEN excluded.timeline_updated_at IS NOT NULL
        THEN excluded.commits_since_release
        WHEN middleman_repo_overviews.latest_release_tag IS excluded.latest_release_tag
        THEN COALESCE(
            excluded.commits_since_release,
            middleman_repo_overviews.commits_since_release
        )
        ELSE excluded.commits_since_release
    END,
    commit_timeline_json = CASE
        WHEN excluded.timeline_updated_at IS NULL
             AND middleman_repo_overviews.latest_release_tag IS excluded.latest_release_tag
        THEN middleman_repo_overviews.commit_timeline_json
        ELSE excluded.commit_timeline_json
    END,
    releases_json = excluded.releases_json,
    timeline_updated_at = CASE
        WHEN excluded.timeline_updated_at IS NOT NULL
        THEN excluded.timeline_updated_at
        WHEN middleman_repo_overviews.latest_release_tag IS excluded.latest_release_tag
        THEN middleman_repo_overviews.timeline_updated_at
        ELSE excluded.timeline_updated_at
    END,
    updated_at = excluded.updated_at
`

type UpsertRepoOverviewParams struct {
	RepoID                   int64
	LatestReleaseTag         string
	LatestReleaseName        string
	LatestReleaseUrl         string
	LatestReleaseTarget      string
	LatestReleasePrerelease  int64
	LatestReleasePublishedAt sql.NullTime
	CommitsSinceRelease      sql.NullInt64
	CommitTimelineJson       string
	ReleasesJson             string
	TimelineUpdatedAt        sql.NullTime
	UpdatedAt                time.Time
}

func (q *Queries) UpsertRepoOverview(ctx context.Context, arg UpsertRepoOverviewParams) error {
	_, err := q.db.ExecContext(ctx, upsertRepoOverview,
		arg.RepoID,
		arg.LatestReleaseTag,
		arg.LatestReleaseName,
		arg.LatestReleaseUrl,
		arg.LatestReleaseTarget,
		arg.LatestReleasePrerelease,
		arg.LatestReleasePublishedAt,
		arg.CommitsSinceRelease,
		arg.CommitTimelineJson,
		arg.ReleasesJson,
		arg.TimelineUpdatedAt,
		arg.UpdatedAt,
	)
	return err
}
