-- Code generated by make db-schema-generate; DO NOT EDIT.
-- Runtime migrations in internal/db/migrations remain the source of truth.

-- internal/db/migrations/000001_initial_schema.up.sql
CREATE TABLE IF NOT EXISTS middleman_repos (
    id                    INTEGER PRIMARY KEY AUTOINCREMENT,
    platform              TEXT NOT NULL DEFAULT 'github',
    platform_host         TEXT NOT NULL DEFAULT 'github.com',
    owner                 TEXT NOT NULL,
    name                  TEXT NOT NULL,
    last_sync_started_at  DATETIME,
    last_sync_completed_at DATETIME,
    last_sync_error       TEXT DEFAULT '',
    allow_squash_merge    INTEGER NOT NULL DEFAULT 1,
    allow_merge_commit    INTEGER NOT NULL DEFAULT 1,
    allow_rebase_merge    INTEGER NOT NULL DEFAULT 1,
    created_at            DATETIME NOT NULL DEFAULT (datetime('now')),
    UNIQUE(platform, platform_host, owner, name)
);

CREATE TABLE IF NOT EXISTS middleman_merge_requests (
    id               INTEGER PRIMARY KEY AUTOINCREMENT,
    repo_id          INTEGER NOT NULL REFERENCES middleman_repos(id) ON DELETE CASCADE,
    platform_id      INTEGER NOT NULL,
    number           INTEGER NOT NULL,
    url              TEXT NOT NULL DEFAULT '',
    title            TEXT NOT NULL DEFAULT '',
    author           TEXT NOT NULL DEFAULT '',
    author_display_name TEXT NOT NULL DEFAULT '',
    state            TEXT NOT NULL DEFAULT 'open',
    is_draft         INTEGER NOT NULL DEFAULT 0,
    body             TEXT NOT NULL DEFAULT '',
    head_branch      TEXT NOT NULL DEFAULT '',
    base_branch      TEXT NOT NULL DEFAULT '',
    additions        INTEGER NOT NULL DEFAULT 0,
    deletions        INTEGER NOT NULL DEFAULT 0,
    comment_count    INTEGER NOT NULL DEFAULT 0,
    review_decision  TEXT NOT NULL DEFAULT '',
    ci_status        TEXT NOT NULL DEFAULT '',
    ci_checks_json   TEXT NOT NULL DEFAULT '',
    platform_head_sha TEXT NOT NULL DEFAULT '',
    platform_base_sha TEXT NOT NULL DEFAULT '',
    diff_head_sha    TEXT NOT NULL DEFAULT '',
    diff_base_sha    TEXT NOT NULL DEFAULT '',
    merge_base_sha   TEXT NOT NULL DEFAULT '',
    head_repo_clone_url TEXT NOT NULL DEFAULT '',
    mergeable_state  TEXT NOT NULL DEFAULT '',
    created_at       DATETIME NOT NULL,
    updated_at       DATETIME NOT NULL,
    last_activity_at DATETIME NOT NULL,
    merged_at        DATETIME,
    closed_at        DATETIME,
    UNIQUE(repo_id, number),
    UNIQUE(repo_id, platform_id)
);

CREATE TABLE IF NOT EXISTS middleman_mr_events (
    id               INTEGER PRIMARY KEY AUTOINCREMENT,
    merge_request_id INTEGER NOT NULL REFERENCES middleman_merge_requests(id) ON DELETE CASCADE,
    platform_id      INTEGER,
    event_type       TEXT NOT NULL,
    author           TEXT NOT NULL DEFAULT '',
    summary          TEXT NOT NULL DEFAULT '',
    body             TEXT NOT NULL DEFAULT '',
    metadata_json    TEXT NOT NULL DEFAULT '',
    created_at       DATETIME NOT NULL,
    dedupe_key       TEXT NOT NULL,
    UNIQUE(dedupe_key)
);

CREATE TABLE IF NOT EXISTS middleman_kanban_state (
    merge_request_id INTEGER PRIMARY KEY REFERENCES middleman_merge_requests(id) ON DELETE CASCADE,
    status           TEXT NOT NULL DEFAULT 'new',
    updated_at       DATETIME NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_mr_repo_state_activity
    ON middleman_merge_requests(repo_id, state, last_activity_at DESC);
CREATE INDEX IF NOT EXISTS idx_mr_state_activity
    ON middleman_merge_requests(state, last_activity_at DESC);
CREATE INDEX IF NOT EXISTS idx_kanban_status
    ON middleman_kanban_state(status, updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_mr_events_created
    ON middleman_mr_events(merge_request_id, created_at DESC);

CREATE TABLE IF NOT EXISTS middleman_issues (
    id               INTEGER PRIMARY KEY AUTOINCREMENT,
    repo_id          INTEGER NOT NULL REFERENCES middleman_repos(id) ON DELETE CASCADE,
    platform_id      INTEGER NOT NULL,
    number           INTEGER NOT NULL,
    url              TEXT NOT NULL DEFAULT '',
    title            TEXT NOT NULL DEFAULT '',
    author           TEXT NOT NULL DEFAULT '',
    state            TEXT NOT NULL DEFAULT 'open',
    body             TEXT NOT NULL DEFAULT '',
    comment_count    INTEGER NOT NULL DEFAULT 0,
    labels_json      TEXT NOT NULL DEFAULT '',
    created_at       DATETIME NOT NULL,
    updated_at       DATETIME NOT NULL,
    last_activity_at DATETIME NOT NULL,
    closed_at        DATETIME,
    UNIQUE(repo_id, number),
    UNIQUE(repo_id, platform_id)
);

CREATE TABLE IF NOT EXISTS middleman_issue_events (
    id            INTEGER PRIMARY KEY AUTOINCREMENT,
    issue_id      INTEGER NOT NULL REFERENCES middleman_issues(id) ON DELETE CASCADE,
    platform_id   INTEGER,
    event_type    TEXT NOT NULL,
    author        TEXT NOT NULL DEFAULT '',
    summary       TEXT NOT NULL DEFAULT '',
    body          TEXT NOT NULL DEFAULT '',
    metadata_json TEXT NOT NULL DEFAULT '',
    created_at    DATETIME NOT NULL,
    dedupe_key    TEXT NOT NULL,
    UNIQUE(dedupe_key)
);

CREATE TABLE IF NOT EXISTS middleman_starred_items (
    item_type  TEXT NOT NULL,
    repo_id    INTEGER NOT NULL REFERENCES middleman_repos(id) ON DELETE CASCADE,
    number     INTEGER NOT NULL,
    starred_at DATETIME NOT NULL DEFAULT (datetime('now')),
    UNIQUE(item_type, repo_id, number)
);

CREATE TABLE IF NOT EXISTS middleman_mr_worktree_links (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    merge_request_id INTEGER NOT NULL
        REFERENCES middleman_merge_requests(id)
        ON DELETE CASCADE,
    worktree_key TEXT NOT NULL,
    worktree_path TEXT,
    worktree_branch TEXT,
    linked_at TEXT NOT NULL,
    UNIQUE(merge_request_id, worktree_key),
    UNIQUE(worktree_key)
);

CREATE INDEX IF NOT EXISTS idx_mr_worktree_links_key
    ON middleman_mr_worktree_links(worktree_key);

CREATE TABLE IF NOT EXISTS middleman_rate_limits (
    id             INTEGER PRIMARY KEY AUTOINCREMENT,
    platform_host  TEXT NOT NULL UNIQUE,
    requests_hour  INTEGER NOT NULL DEFAULT 0,
    hour_start     DATETIME NOT NULL,
    rate_remaining INTEGER NOT NULL DEFAULT -1,
    rate_reset_at  DATETIME,
    updated_at     DATETIME NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_issues_repo_state_activity
    ON middleman_issues(repo_id, state, last_activity_at DESC);
CREATE INDEX IF NOT EXISTS idx_issues_state_activity
    ON middleman_issues(state, last_activity_at DESC);
CREATE INDEX IF NOT EXISTS idx_issue_events_created
    ON middleman_issue_events(issue_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_starred_items_type
    ON middleman_starred_items(item_type, starred_at DESC);


-- internal/db/migrations/000002_update_mr_events_dedupe.up.sql
CREATE TABLE middleman_mr_events_v2 (
    id               INTEGER PRIMARY KEY AUTOINCREMENT,
    merge_request_id INTEGER NOT NULL REFERENCES middleman_merge_requests(id) ON DELETE CASCADE,
    platform_id      INTEGER,
    event_type       TEXT NOT NULL,
    author           TEXT NOT NULL DEFAULT '',
    summary          TEXT NOT NULL DEFAULT '',
    body             TEXT NOT NULL DEFAULT '',
    metadata_json    TEXT NOT NULL DEFAULT '',
    created_at       DATETIME NOT NULL,
    dedupe_key       TEXT NOT NULL,
    UNIQUE(merge_request_id, dedupe_key)
);

INSERT INTO middleman_mr_events_v2 (
    id,
    merge_request_id,
    platform_id,
    event_type,
    author,
    summary,
    body,
    metadata_json,
    created_at,
    dedupe_key
)
SELECT
    id,
    merge_request_id,
    platform_id,
    event_type,
    author,
    summary,
    body,
    metadata_json,
    created_at,
    dedupe_key
FROM middleman_mr_events;

DROP TABLE middleman_mr_events;
ALTER TABLE middleman_mr_events_v2 RENAME TO middleman_mr_events;
CREATE INDEX IF NOT EXISTS idx_mr_events_created
    ON middleman_mr_events(merge_request_id, created_at DESC);


-- internal/db/migrations/000003_add_backfill_and_detail_columns.up.sql
ALTER TABLE middleman_repos ADD COLUMN backfill_pr_page INTEGER NOT NULL DEFAULT 0;
ALTER TABLE middleman_repos ADD COLUMN backfill_pr_complete INTEGER NOT NULL DEFAULT 0;
ALTER TABLE middleman_repos ADD COLUMN backfill_pr_completed_at DATETIME;
ALTER TABLE middleman_repos ADD COLUMN backfill_issue_page INTEGER NOT NULL DEFAULT 0;
ALTER TABLE middleman_repos ADD COLUMN backfill_issue_complete INTEGER NOT NULL DEFAULT 0;
ALTER TABLE middleman_repos ADD COLUMN backfill_issue_completed_at DATETIME;

ALTER TABLE middleman_merge_requests ADD COLUMN detail_fetched_at DATETIME;
ALTER TABLE middleman_merge_requests ADD COLUMN ci_had_pending INTEGER NOT NULL DEFAULT 0;

ALTER TABLE middleman_issues ADD COLUMN detail_fetched_at DATETIME;

ALTER TABLE middleman_rate_limits ADD COLUMN rate_limit INTEGER NOT NULL DEFAULT -1;


-- internal/db/migrations/000004_drop_legacy_schema_version.up.sql
DROP TABLE IF EXISTS middleman_schema_version;


-- internal/db/migrations/000005_graphql_sync_and_labels.up.sql
-- Rate limits: add api_type column, change UNIQUE constraint
CREATE TABLE middleman_rate_limits_new (
    id             INTEGER PRIMARY KEY AUTOINCREMENT,
    platform_host  TEXT NOT NULL,
    api_type       TEXT NOT NULL DEFAULT 'rest',
    requests_hour  INTEGER NOT NULL DEFAULT 0,
    hour_start     DATETIME NOT NULL,
    rate_remaining INTEGER NOT NULL DEFAULT -1,
    rate_limit     INTEGER NOT NULL DEFAULT -1,
    rate_reset_at  DATETIME,
    updated_at     DATETIME NOT NULL DEFAULT (datetime('now')),
    UNIQUE(platform_host, api_type)
);

INSERT INTO middleman_rate_limits_new
    (id, platform_host, api_type, requests_hour, hour_start,
     rate_remaining, rate_limit, rate_reset_at, updated_at)
SELECT id, platform_host, 'rest', requests_hour, hour_start,
       rate_remaining, rate_limit, rate_reset_at, updated_at
FROM middleman_rate_limits;

DROP TABLE middleman_rate_limits;

ALTER TABLE middleman_rate_limits_new RENAME TO middleman_rate_limits;

-- Normalized labels
CREATE TABLE IF NOT EXISTS middleman_labels (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    repo_id     INTEGER NOT NULL REFERENCES middleman_repos(id) ON DELETE CASCADE,
    platform_id INTEGER,
    name        TEXT NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    color       TEXT NOT NULL DEFAULT '',
    is_default  INTEGER NOT NULL DEFAULT 0,
    updated_at  DATETIME NOT NULL,
    UNIQUE(repo_id, name),
    UNIQUE(repo_id, platform_id)
);

CREATE TABLE IF NOT EXISTS middleman_merge_request_labels (
    merge_request_id INTEGER NOT NULL REFERENCES middleman_merge_requests(id) ON DELETE CASCADE,
    label_id         INTEGER NOT NULL REFERENCES middleman_labels(id) ON DELETE CASCADE,
    PRIMARY KEY (merge_request_id, label_id)
);

CREATE TABLE IF NOT EXISTS middleman_issue_labels (
    issue_id  INTEGER NOT NULL REFERENCES middleman_issues(id) ON DELETE CASCADE,
    label_id  INTEGER NOT NULL REFERENCES middleman_labels(id) ON DELETE CASCADE,
    PRIMARY KEY (issue_id, label_id)
);

CREATE INDEX IF NOT EXISTS idx_labels_repo_name
    ON middleman_labels(repo_id, name);
CREATE INDEX IF NOT EXISTS idx_labels_repo_platform_id
    ON middleman_labels(repo_id, platform_id)
    WHERE platform_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_merge_request_labels_label_id
    ON middleman_merge_request_labels(label_id);
CREATE INDEX IF NOT EXISTS idx_issue_labels_label_id
    ON middleman_issue_labels(label_id);

WITH parsed_issue_labels AS (
    SELECT
        i.id AS issue_id,
        i.repo_id,
        json_extract(label.value, '$.name') AS name,
        COALESCE(json_extract(label.value, '$.color'), '') AS color,
        COALESCE(i.updated_at, i.created_at, datetime('now')) AS updated_at
    FROM middleman_issues AS i
    JOIN json_each(
        CASE
            WHEN json_valid(i.labels_json) THEN i.labels_json
            ELSE '[]'
        END
    ) AS label
    WHERE TRIM(COALESCE(json_extract(label.value, '$.name'), '')) <> ''
)
INSERT OR IGNORE INTO middleman_labels (repo_id, platform_id, name, description, color, is_default, updated_at)
SELECT
    repo_id,
    NULL,
    name,
    '',
    MIN(color) AS color,
    0,
    MAX(updated_at) AS updated_at
FROM parsed_issue_labels
GROUP BY repo_id, name;

WITH parsed_issue_labels AS (
    SELECT
        i.id AS issue_id,
        i.repo_id,
        json_extract(label.value, '$.name') AS name
    FROM middleman_issues AS i
    JOIN json_each(
        CASE
            WHEN json_valid(i.labels_json) THEN i.labels_json
            ELSE '[]'
        END
    ) AS label
    WHERE TRIM(COALESCE(json_extract(label.value, '$.name'), '')) <> ''
)
INSERT OR IGNORE INTO middleman_issue_labels (issue_id, label_id)
SELECT
    pil.issue_id,
    l.id
FROM parsed_issue_labels AS pil
JOIN middleman_labels AS l
    ON l.repo_id = pil.repo_id
   AND l.name = pil.name;


-- internal/db/migrations/000006_add_stacks.up.sql
CREATE TABLE IF NOT EXISTS middleman_stacks (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    repo_id INTEGER NOT NULL REFERENCES middleman_repos(id) ON DELETE CASCADE,
    base_number INTEGER NOT NULL,
    name TEXT NOT NULL,
    created_at DATETIME NOT NULL DEFAULT (datetime('now')),
    updated_at DATETIME NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS middleman_stack_members (
    stack_id INTEGER NOT NULL REFERENCES middleman_stacks(id) ON DELETE CASCADE,
    merge_request_id INTEGER NOT NULL REFERENCES middleman_merge_requests(id) ON DELETE CASCADE,
    position INTEGER NOT NULL,
    PRIMARY KEY (stack_id, merge_request_id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_stack_members_mr
    ON middleman_stack_members(merge_request_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_stacks_repo_base
    ON middleman_stacks(repo_id, base_number);
CREATE INDEX IF NOT EXISTS idx_stacks_repo
    ON middleman_stacks(repo_id);


-- internal/db/migrations/000007_add_workspaces.up.sql
CREATE TABLE IF NOT EXISTS middleman_workspaces (
    id            TEXT PRIMARY KEY,
    platform_host TEXT NOT NULL,
    repo_owner    TEXT NOT NULL,
    repo_name     TEXT NOT NULL,
    mr_number     INTEGER NOT NULL,
    mr_head_ref   TEXT NOT NULL,
    mr_head_repo  TEXT,
    worktree_path TEXT NOT NULL,
    tmux_session  TEXT NOT NULL,
    status        TEXT NOT NULL DEFAULT 'creating',
    error_message TEXT,
    created_at    DATETIME NOT NULL DEFAULT (datetime('now')),
    UNIQUE(platform_host, repo_owner, repo_name, mr_number)
);


-- internal/db/migrations/000008_casefold_repo_identifiers.up.sql
CREATE TEMP TABLE repo_casefold_duplicates AS
SELECT
    r.id AS duplicate_id,
    keep.keep_id
FROM middleman_repos AS r
JOIN (
    SELECT
        platform,
        lower(platform_host) AS platform_host,
        lower(owner) AS owner,
        lower(name) AS name,
        min(id) AS keep_id,
        count(*) AS repo_count
    FROM middleman_repos
    GROUP BY platform, lower(platform_host), lower(owner), lower(name)
    HAVING repo_count > 1
) AS keep
    ON keep.platform = r.platform
   AND keep.platform_host = lower(r.platform_host)
   AND keep.owner = lower(r.owner)
   AND keep.name = lower(r.name)
WHERE r.id <> keep.keep_id;

CREATE TEMP TABLE repo_casefold_targets AS
SELECT
    r.id AS repo_id,
    COALESCE(d.keep_id, r.id) AS keep_id
FROM middleman_repos AS r
LEFT JOIN repo_casefold_duplicates AS d
    ON d.duplicate_id = r.id;

CREATE TEMP TABLE label_casefold_duplicates AS
SELECT id AS duplicate_id, keep_id
FROM (
    SELECT
        l.id,
        first_value(l.id) OVER (
            PARTITION BY t.keep_id, l.name
            ORDER BY
                CASE WHEN l.platform_id IS NOT NULL THEN 0 ELSE 1 END,
                CASE WHEN l.repo_id = t.keep_id THEN 0 ELSE 1 END,
                l.id
        ) AS keep_id,
        row_number() OVER (
            PARTITION BY t.keep_id, l.name
            ORDER BY
                CASE WHEN l.platform_id IS NOT NULL THEN 0 ELSE 1 END,
                CASE WHEN l.repo_id = t.keep_id THEN 0 ELSE 1 END,
                l.id
        ) AS rn
    FROM middleman_labels AS l
    JOIN repo_casefold_targets AS t
        ON t.repo_id = l.repo_id
)
WHERE rn > 1;

INSERT OR IGNORE INTO middleman_issue_labels (issue_id, label_id)
SELECT il.issue_id, d.keep_id
FROM middleman_issue_labels AS il
JOIN label_casefold_duplicates AS d
    ON d.duplicate_id = il.label_id;

INSERT OR IGNORE INTO middleman_merge_request_labels (merge_request_id, label_id)
SELECT mrl.merge_request_id, d.keep_id
FROM middleman_merge_request_labels AS mrl
JOIN label_casefold_duplicates AS d
    ON d.duplicate_id = mrl.label_id;

DELETE FROM middleman_issue_labels
WHERE label_id IN (
    SELECT duplicate_id FROM label_casefold_duplicates
);

DELETE FROM middleman_merge_request_labels
WHERE label_id IN (
    SELECT duplicate_id FROM label_casefold_duplicates
);

DELETE FROM middleman_labels
WHERE id IN (
    SELECT duplicate_id FROM label_casefold_duplicates
);

CREATE TEMP TABLE issue_casefold_duplicates AS
SELECT id AS duplicate_id, keep_id
FROM (
    SELECT
        i.id,
        first_value(i.id) OVER (
            PARTITION BY t.keep_id, i.number
            ORDER BY CASE WHEN i.repo_id = t.keep_id THEN 0 ELSE 1 END, i.id
        ) AS keep_id,
        row_number() OVER (
            PARTITION BY t.keep_id, i.number
            ORDER BY CASE WHEN i.repo_id = t.keep_id THEN 0 ELSE 1 END, i.id
        ) AS rn
    FROM middleman_issues AS i
    JOIN repo_casefold_targets AS t
        ON t.repo_id = i.repo_id
)
WHERE rn > 1;

CREATE TEMP TABLE issue_event_casefold_winners AS
SELECT event_id, keep_id
FROM (
    SELECT
        e.id AS event_id,
        d.keep_id,
        row_number() OVER (
            PARTITION BY d.keep_id, e.dedupe_key
            ORDER BY e.id
        ) AS rn
    FROM middleman_issue_events AS e
    JOIN issue_casefold_duplicates AS d
        ON d.duplicate_id = e.issue_id
    WHERE NOT EXISTS (
        SELECT 1
        FROM middleman_issue_events AS existing
        WHERE existing.issue_id = d.keep_id
          AND existing.dedupe_key = e.dedupe_key
    )
)
WHERE rn = 1;

UPDATE middleman_issue_events
SET issue_id = (
    SELECT keep_id
    FROM issue_event_casefold_winners
    WHERE event_id = middleman_issue_events.id
)
WHERE id IN (
    SELECT event_id FROM issue_event_casefold_winners
);

INSERT OR IGNORE INTO middleman_issue_labels (
    issue_id, label_id
)
SELECT d.keep_id, il.label_id
FROM middleman_issue_labels AS il
JOIN issue_casefold_duplicates AS d
    ON d.duplicate_id = il.issue_id;

DELETE FROM middleman_issue_events
WHERE issue_id IN (
    SELECT duplicate_id FROM issue_casefold_duplicates
);

DELETE FROM middleman_issue_labels
WHERE issue_id IN (
    SELECT duplicate_id FROM issue_casefold_duplicates
);

DELETE FROM middleman_issues
WHERE id IN (
    SELECT duplicate_id FROM issue_casefold_duplicates
);

CREATE TEMP TABLE mr_casefold_duplicates AS
SELECT id AS duplicate_id, keep_id
FROM (
    SELECT
        mr.id,
        first_value(mr.id) OVER (
            PARTITION BY t.keep_id, mr.number
            ORDER BY CASE WHEN mr.repo_id = t.keep_id THEN 0 ELSE 1 END, mr.id
        ) AS keep_id,
        row_number() OVER (
            PARTITION BY t.keep_id, mr.number
            ORDER BY CASE WHEN mr.repo_id = t.keep_id THEN 0 ELSE 1 END, mr.id
        ) AS rn
    FROM middleman_merge_requests AS mr
    JOIN repo_casefold_targets AS t
        ON t.repo_id = mr.repo_id
)
WHERE rn > 1;

CREATE TEMP TABLE mr_event_casefold_winners AS
SELECT event_id, keep_id
FROM (
    SELECT
        e.id AS event_id,
        d.keep_id,
        row_number() OVER (
            PARTITION BY d.keep_id, e.dedupe_key
            ORDER BY e.id
        ) AS rn
    FROM middleman_mr_events AS e
    JOIN mr_casefold_duplicates AS d
        ON d.duplicate_id = e.merge_request_id
    WHERE NOT EXISTS (
        SELECT 1
        FROM middleman_mr_events AS existing
        WHERE existing.merge_request_id = d.keep_id
          AND existing.dedupe_key = e.dedupe_key
    )
)
WHERE rn = 1;

UPDATE middleman_mr_events
SET merge_request_id = (
    SELECT keep_id
    FROM mr_event_casefold_winners
    WHERE event_id = middleman_mr_events.id
)
WHERE id IN (
    SELECT event_id FROM mr_event_casefold_winners
);

CREATE TEMP TABLE mr_casefold_kanban_winners AS
SELECT keep_id, status, updated_at
FROM (
    SELECT
        candidates.keep_id,
        ks.status,
        ks.updated_at,
        row_number() OVER (
            PARTITION BY candidates.keep_id
            ORDER BY
                CASE WHEN ks.status <> 'new' THEN 0 ELSE 1 END,
                julianday(ks.updated_at) DESC,
                ks.updated_at DESC,
                ks.status ASC
        ) AS rn
    FROM (
        SELECT keep_id, keep_id AS merge_request_id
        FROM mr_casefold_duplicates
        UNION
        SELECT keep_id, duplicate_id AS merge_request_id
        FROM mr_casefold_duplicates
    ) AS candidates
    JOIN middleman_kanban_state AS ks
        ON ks.merge_request_id = candidates.merge_request_id
)
WHERE rn = 1;

UPDATE middleman_kanban_state
SET
    status = (
        SELECT status
        FROM mr_casefold_kanban_winners
        WHERE keep_id = middleman_kanban_state.merge_request_id
    ),
    updated_at = (
        SELECT updated_at
        FROM mr_casefold_kanban_winners
        WHERE keep_id = middleman_kanban_state.merge_request_id
    )
WHERE merge_request_id IN (
    SELECT keep_id FROM mr_casefold_kanban_winners
);

INSERT OR IGNORE INTO middleman_kanban_state (
    merge_request_id, status, updated_at
)
SELECT keep_id, status, updated_at
FROM mr_casefold_kanban_winners;

INSERT OR IGNORE INTO middleman_merge_request_labels (
    merge_request_id, label_id
)
SELECT d.keep_id, mrl.label_id
FROM middleman_merge_request_labels AS mrl
JOIN mr_casefold_duplicates AS d
    ON d.duplicate_id = mrl.merge_request_id;

UPDATE middleman_mr_worktree_links
SET merge_request_id = (
    SELECT keep_id
    FROM mr_casefold_duplicates
    WHERE duplicate_id = middleman_mr_worktree_links.merge_request_id
)
WHERE merge_request_id IN (
    SELECT duplicate_id FROM mr_casefold_duplicates
)
AND NOT EXISTS (
    SELECT 1
    FROM middleman_mr_worktree_links AS existing
    JOIN mr_casefold_duplicates AS d
        ON d.duplicate_id = middleman_mr_worktree_links.merge_request_id
    WHERE existing.merge_request_id = d.keep_id
      AND existing.worktree_key = middleman_mr_worktree_links.worktree_key
);

DELETE FROM middleman_mr_worktree_links
WHERE merge_request_id IN (
    SELECT duplicate_id FROM mr_casefold_duplicates
);

DELETE FROM middleman_stack_members
WHERE merge_request_id IN (
    SELECT duplicate_id FROM mr_casefold_duplicates
)
AND EXISTS (
    SELECT 1
    FROM middleman_stack_members AS existing
    JOIN mr_casefold_duplicates AS d
        ON d.duplicate_id = middleman_stack_members.merge_request_id
    WHERE existing.merge_request_id = d.keep_id
);

UPDATE middleman_stack_members
SET merge_request_id = (
    SELECT keep_id
    FROM mr_casefold_duplicates
    WHERE duplicate_id = middleman_stack_members.merge_request_id
)
WHERE merge_request_id IN (
    SELECT duplicate_id FROM mr_casefold_duplicates
);

DELETE FROM middleman_mr_events
WHERE merge_request_id IN (
    SELECT duplicate_id FROM mr_casefold_duplicates
);

DELETE FROM middleman_kanban_state
WHERE merge_request_id IN (
    SELECT duplicate_id FROM mr_casefold_duplicates
);

DELETE FROM middleman_merge_request_labels
WHERE merge_request_id IN (
    SELECT duplicate_id FROM mr_casefold_duplicates
);

DELETE FROM middleman_merge_requests
WHERE id IN (
    SELECT duplicate_id FROM mr_casefold_duplicates
);

DELETE FROM middleman_issues
WHERE id IN (
    SELECT id
    FROM (
        SELECT
            i.id,
            row_number() OVER (
                PARTITION BY t.keep_id, i.platform_id
                ORDER BY CASE WHEN i.repo_id = t.keep_id THEN 0 ELSE 1 END, i.id
            ) AS rn
        FROM middleman_issues AS i
        JOIN repo_casefold_targets AS t
            ON t.repo_id = i.repo_id
    )
    WHERE rn > 1
);

DELETE FROM middleman_merge_requests
WHERE id IN (
    SELECT id
    FROM (
        SELECT
            mr.id,
            row_number() OVER (
                PARTITION BY t.keep_id, mr.platform_id
                ORDER BY CASE WHEN mr.repo_id = t.keep_id THEN 0 ELSE 1 END, mr.id
            ) AS rn
        FROM middleman_merge_requests AS mr
        JOIN repo_casefold_targets AS t
            ON t.repo_id = mr.repo_id
    )
    WHERE rn > 1
);

CREATE TEMP TABLE label_platform_casefold_duplicates AS
SELECT id AS duplicate_id, keep_id
FROM (
    SELECT
        l.id,
        first_value(l.id) OVER (
            PARTITION BY t.keep_id, l.platform_id
            ORDER BY CASE WHEN l.repo_id = t.keep_id THEN 0 ELSE 1 END, l.id
        ) AS keep_id,
        row_number() OVER (
            PARTITION BY t.keep_id, l.platform_id
            ORDER BY CASE WHEN l.repo_id = t.keep_id THEN 0 ELSE 1 END, l.id
        ) AS rn
    FROM middleman_labels AS l
    JOIN repo_casefold_targets AS t
        ON t.repo_id = l.repo_id
    WHERE l.platform_id IS NOT NULL
)
WHERE rn > 1;

INSERT OR IGNORE INTO middleman_issue_labels (issue_id, label_id)
SELECT il.issue_id, d.keep_id
FROM middleman_issue_labels AS il
JOIN label_platform_casefold_duplicates AS d
    ON d.duplicate_id = il.label_id;

INSERT OR IGNORE INTO middleman_merge_request_labels (
    merge_request_id, label_id
)
SELECT mrl.merge_request_id, d.keep_id
FROM middleman_merge_request_labels AS mrl
JOIN label_platform_casefold_duplicates AS d
    ON d.duplicate_id = mrl.label_id;

DELETE FROM middleman_issue_labels
WHERE label_id IN (
    SELECT duplicate_id FROM label_platform_casefold_duplicates
);

DELETE FROM middleman_merge_request_labels
WHERE label_id IN (
    SELECT duplicate_id FROM label_platform_casefold_duplicates
);

DELETE FROM middleman_labels
WHERE id IN (
    SELECT duplicate_id FROM label_platform_casefold_duplicates
);

DELETE FROM middleman_starred_items
WHERE rowid IN (
    SELECT rowid
    FROM (
        SELECT
            si.rowid,
            row_number() OVER (
                PARTITION BY t.keep_id, si.item_type, si.number
                ORDER BY CASE WHEN si.repo_id = t.keep_id THEN 0 ELSE 1 END, si.rowid
            ) AS rn
        FROM middleman_starred_items AS si
        JOIN repo_casefold_targets AS t
            ON t.repo_id = si.repo_id
    )
    WHERE rn > 1
);

CREATE TEMP TABLE stack_casefold_duplicates AS
SELECT id AS duplicate_id, keep_id
FROM (
    SELECT
        s.id,
        first_value(s.id) OVER (
            PARTITION BY t.keep_id, s.base_number
            ORDER BY CASE WHEN s.repo_id = t.keep_id THEN 0 ELSE 1 END, s.id
        ) AS keep_id,
        row_number() OVER (
            PARTITION BY t.keep_id, s.base_number
            ORDER BY CASE WHEN s.repo_id = t.keep_id THEN 0 ELSE 1 END, s.id
        ) AS rn
    FROM middleman_stacks AS s
    JOIN repo_casefold_targets AS t
        ON t.repo_id = s.repo_id
)
WHERE rn > 1;

INSERT OR IGNORE INTO middleman_stack_members (
    stack_id, merge_request_id, position
)
SELECT d.keep_id, sm.merge_request_id, sm.position
FROM middleman_stack_members AS sm
JOIN stack_casefold_duplicates AS d
    ON d.duplicate_id = sm.stack_id;

DELETE FROM middleman_stack_members
WHERE stack_id IN (
    SELECT duplicate_id FROM stack_casefold_duplicates
);

DELETE FROM middleman_stacks
WHERE id IN (
    SELECT duplicate_id FROM stack_casefold_duplicates
);

UPDATE middleman_merge_requests
SET repo_id = (
    SELECT keep_id
    FROM repo_casefold_targets
    WHERE repo_id = middleman_merge_requests.repo_id
)
WHERE repo_id IN (
    SELECT duplicate_id FROM repo_casefold_duplicates
);

UPDATE middleman_issues
SET repo_id = (
    SELECT keep_id
    FROM repo_casefold_targets
    WHERE repo_id = middleman_issues.repo_id
)
WHERE repo_id IN (
    SELECT duplicate_id FROM repo_casefold_duplicates
);

UPDATE middleman_labels
SET repo_id = (
    SELECT keep_id
    FROM repo_casefold_targets
    WHERE repo_id = middleman_labels.repo_id
)
WHERE repo_id IN (
    SELECT duplicate_id FROM repo_casefold_duplicates
);

UPDATE middleman_starred_items
SET repo_id = (
    SELECT keep_id
    FROM repo_casefold_targets
    WHERE repo_id = middleman_starred_items.repo_id
)
WHERE repo_id IN (
    SELECT duplicate_id FROM repo_casefold_duplicates
);

UPDATE middleman_stacks
SET repo_id = (
    SELECT keep_id
    FROM repo_casefold_targets
    WHERE repo_id = middleman_stacks.repo_id
)
WHERE repo_id IN (
    SELECT duplicate_id FROM repo_casefold_duplicates
);

DELETE FROM middleman_workspaces
WHERE rowid NOT IN (
    SELECT min(rowid)
    FROM middleman_workspaces
    GROUP BY lower(platform_host), lower(repo_owner), lower(repo_name), mr_number
);

DELETE FROM middleman_repos
WHERE id IN (
    SELECT duplicate_id FROM repo_casefold_duplicates
);

UPDATE middleman_repos
SET
    platform_host = lower(platform_host),
    owner = lower(owner),
    name = lower(name);

UPDATE middleman_workspaces
SET
    platform_host = lower(platform_host),
    repo_owner = lower(repo_owner),
    repo_name = lower(repo_name);

DROP TABLE stack_casefold_duplicates;
DROP TABLE mr_event_casefold_winners;
DROP TABLE mr_casefold_duplicates;
DROP TABLE issue_event_casefold_winners;
DROP TABLE issue_casefold_duplicates;
DROP TABLE label_casefold_duplicates;
DROP TABLE repo_casefold_targets;
DROP TABLE repo_casefold_duplicates;


-- internal/db/migrations/000009_casefold_identifier_triggers.up.sql
CREATE TRIGGER IF NOT EXISTS middleman_repos_casefold_insert
BEFORE INSERT ON middleman_repos
WHEN NEW.platform_host <> lower(NEW.platform_host)
  OR NEW.owner <> lower(NEW.owner)
  OR NEW.name <> lower(NEW.name)
BEGIN
    SELECT RAISE(ABORT, 'repo identifiers must be lowercase');
END;

CREATE TRIGGER IF NOT EXISTS middleman_repos_casefold_update
BEFORE UPDATE OF platform_host, owner, name ON middleman_repos
WHEN NEW.platform_host <> lower(NEW.platform_host)
  OR NEW.owner <> lower(NEW.owner)
  OR NEW.name <> lower(NEW.name)
BEGIN
    SELECT RAISE(ABORT, 'repo identifiers must be lowercase');
END;

CREATE TRIGGER IF NOT EXISTS middleman_workspaces_casefold_insert
BEFORE INSERT ON middleman_workspaces
WHEN NEW.platform_host <> lower(NEW.platform_host)
  OR NEW.repo_owner <> lower(NEW.repo_owner)
  OR NEW.repo_name <> lower(NEW.repo_name)
BEGIN
    SELECT RAISE(ABORT, 'workspace repo identifiers must be lowercase');
END;

CREATE TRIGGER IF NOT EXISTS middleman_workspaces_casefold_update
BEFORE UPDATE OF platform_host, repo_owner, repo_name ON middleman_workspaces
WHEN NEW.platform_host <> lower(NEW.platform_host)
  OR NEW.repo_owner <> lower(NEW.repo_owner)
  OR NEW.repo_name <> lower(NEW.repo_name)
BEGIN
    SELECT RAISE(ABORT, 'workspace repo identifiers must be lowercase');
END;


-- internal/db/migrations/000010_timestamp_repair_gate.up.sql
-- Version gate for the one-time legacy timestamp repair that runs from Go
-- immediately after upgrading databases from schema versions below 10.


-- internal/db/migrations/000011_add_workspace_setup_events.up.sql
CREATE TABLE IF NOT EXISTS middleman_workspace_setup_events (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    workspace_id TEXT NOT NULL REFERENCES middleman_workspaces(id) ON DELETE CASCADE,
    stage       TEXT NOT NULL,
    outcome     TEXT NOT NULL,
    message     TEXT NOT NULL,
    created_at  DATETIME NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS middleman_workspace_setup_events_workspace_id_idx
    ON middleman_workspace_setup_events (workspace_id, id);

ALTER TABLE middleman_workspaces
    ADD COLUMN workspace_branch TEXT NOT NULL DEFAULT '__middleman_unknown__';


-- internal/db/migrations/000012_workspace_item_types.up.sql
DROP TRIGGER IF EXISTS middleman_workspaces_casefold_update;
DROP TRIGGER IF EXISTS middleman_workspaces_casefold_insert;

CREATE TEMP TABLE middleman_workspace_setup_events_backup AS
SELECT id, workspace_id, stage, outcome, message, created_at
FROM middleman_workspace_setup_events;

DROP INDEX IF EXISTS middleman_workspace_setup_events_workspace_id_idx;
DROP TABLE IF EXISTS middleman_workspace_setup_events;

ALTER TABLE middleman_workspaces
    RENAME TO middleman_workspaces_v11;

CREATE TABLE middleman_workspaces (
    id               TEXT PRIMARY KEY,
    platform_host    TEXT NOT NULL,
    repo_owner       TEXT NOT NULL,
    repo_name        TEXT NOT NULL,
    item_type        TEXT NOT NULL DEFAULT 'pull_request',
    item_number      INTEGER NOT NULL,
    git_head_ref     TEXT NOT NULL,
    mr_head_repo     TEXT,
    worktree_path    TEXT NOT NULL,
    tmux_session     TEXT NOT NULL,
    status           TEXT NOT NULL DEFAULT 'creating',
    error_message    TEXT,
    created_at       DATETIME NOT NULL DEFAULT (datetime('now')),
    workspace_branch TEXT NOT NULL DEFAULT '__middleman_unknown__',
    UNIQUE(platform_host, repo_owner, repo_name, item_type, item_number)
);

INSERT INTO middleman_workspaces (
    id, platform_host, repo_owner, repo_name,
    item_type, item_number, git_head_ref, mr_head_repo,
    worktree_path, tmux_session, status,
    error_message, created_at, workspace_branch
)
SELECT
    id, platform_host, repo_owner, repo_name,
    'pull_request', mr_number, mr_head_ref, mr_head_repo,
    worktree_path, tmux_session, status,
    error_message, created_at, workspace_branch
FROM middleman_workspaces_v11;

DROP TABLE middleman_workspaces_v11;

CREATE TRIGGER middleman_workspaces_casefold_insert
BEFORE INSERT ON middleman_workspaces
WHEN NEW.platform_host <> lower(NEW.platform_host)
  OR NEW.repo_owner <> lower(NEW.repo_owner)
  OR NEW.repo_name <> lower(NEW.repo_name)
BEGIN
    SELECT RAISE(ABORT, 'workspace repo identifiers must be lowercase');
END;

CREATE TRIGGER middleman_workspaces_casefold_update
BEFORE UPDATE OF platform_host, repo_owner, repo_name ON middleman_workspaces
WHEN NEW.platform_host <> lower(NEW.platform_host)
  OR NEW.repo_owner <> lower(NEW.repo_owner)
  OR NEW.repo_name <> lower(NEW.repo_name)
BEGIN
    SELECT RAISE(ABORT, 'workspace repo identifiers must be lowercase');
END;

CREATE TABLE middleman_workspace_setup_events (
    id           INTEGER PRIMARY KEY AUTOINCREMENT,
    workspace_id TEXT NOT NULL REFERENCES middleman_workspaces(id) ON DELETE CASCADE,
    stage        TEXT NOT NULL,
    outcome      TEXT NOT NULL,
    message      TEXT NOT NULL,
    created_at   DATETIME NOT NULL DEFAULT (datetime('now'))
);

INSERT INTO middleman_workspace_setup_events (
    id, workspace_id, stage, outcome, message, created_at
)
SELECT
    id, workspace_id, stage, outcome, message, created_at
FROM middleman_workspace_setup_events_backup;

DROP TABLE middleman_workspace_setup_events_backup;

CREATE INDEX middleman_workspace_setup_events_workspace_id_idx
    ON middleman_workspace_setup_events (workspace_id, id);


-- internal/db/migrations/000013_workspace_tmux_sessions.up.sql
CREATE TABLE IF NOT EXISTS middleman_workspace_tmux_sessions (
    workspace_id TEXT NOT NULL REFERENCES middleman_workspaces(id) ON DELETE CASCADE,
    session_name TEXT NOT NULL,
    target_key   TEXT NOT NULL,
    created_at   DATETIME NOT NULL DEFAULT (datetime('now')),
    PRIMARY KEY (workspace_id, session_name),
    UNIQUE (session_name)
);

CREATE INDEX IF NOT EXISTS middleman_workspace_tmux_sessions_workspace_id_idx
    ON middleman_workspace_tmux_sessions(workspace_id);


-- internal/db/migrations/000014_repo_overviews.up.sql
CREATE TABLE IF NOT EXISTS middleman_repo_overviews (
    repo_id                  INTEGER PRIMARY KEY REFERENCES middleman_repos(id) ON DELETE CASCADE,
    latest_release_tag       TEXT NOT NULL DEFAULT '',
    latest_release_name      TEXT NOT NULL DEFAULT '',
    latest_release_url       TEXT NOT NULL DEFAULT '',
    latest_release_target    TEXT NOT NULL DEFAULT '',
    latest_release_prerelease INTEGER NOT NULL DEFAULT 0,
    latest_release_published_at DATETIME,
    commits_since_release    INTEGER,
    commit_timeline_json     TEXT NOT NULL DEFAULT '[]',
    timeline_updated_at      DATETIME,
    updated_at               DATETIME NOT NULL DEFAULT (datetime('now'))
);


-- internal/db/migrations/000015_repo_overview_releases.up.sql
CREATE TABLE middleman_repo_overviews_new (
    repo_id                  INTEGER PRIMARY KEY REFERENCES middleman_repos(id) ON DELETE CASCADE,
    latest_release_tag       TEXT NOT NULL DEFAULT '',
    latest_release_name      TEXT NOT NULL DEFAULT '',
    latest_release_url       TEXT NOT NULL DEFAULT '',
    latest_release_target    TEXT NOT NULL DEFAULT '',
    latest_release_prerelease INTEGER NOT NULL DEFAULT 0,
    latest_release_published_at DATETIME,
    commits_since_release    INTEGER,
    commit_timeline_json     TEXT NOT NULL DEFAULT '[]',
    releases_json            TEXT NOT NULL DEFAULT '[]',
    timeline_updated_at      DATETIME,
    updated_at               DATETIME NOT NULL DEFAULT (datetime('now'))
);

INSERT INTO middleman_repo_overviews_new (
    repo_id,
    latest_release_tag,
    latest_release_name,
    latest_release_url,
    latest_release_target,
    latest_release_prerelease,
    latest_release_published_at,
    commits_since_release,
    commit_timeline_json,
    timeline_updated_at,
    updated_at
)
SELECT
    repo_id,
    latest_release_tag,
    latest_release_name,
    latest_release_url,
    latest_release_target,
    latest_release_prerelease,
    latest_release_published_at,
    commits_since_release,
    commit_timeline_json,
    timeline_updated_at,
    updated_at
FROM middleman_repo_overviews;

DROP TABLE middleman_repo_overviews;
ALTER TABLE middleman_repo_overviews_new RENAME TO middleman_repo_overviews;


-- internal/db/migrations/000016_workspace_associated_pr.up.sql
ALTER TABLE middleman_workspaces
    ADD COLUMN associated_pr_number INTEGER;
