// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stacks.sql

package sqlc

import (
	"context"
	"strings"
	"time"
)

const deleteAllStacksForRepo = `-- name: DeleteAllStacksForRepo :exec
DELETE FROM middleman_stacks
WHERE repo_id = ?1
`

func (q *Queries) DeleteAllStacksForRepo(ctx context.Context, repoID int64) error {
	_, err := q.db.ExecContext(ctx, deleteAllStacksForRepo, repoID)
	return err
}

const deleteStackMemberByMR = `-- name: DeleteStackMemberByMR :exec
DELETE FROM middleman_stack_members
WHERE merge_request_id = ?1
`

func (q *Queries) DeleteStackMemberByMR(ctx context.Context, mergeRequestID int64) error {
	_, err := q.db.ExecContext(ctx, deleteStackMemberByMR, mergeRequestID)
	return err
}

const deleteStackMembersByStack = `-- name: DeleteStackMembersByStack :exec
DELETE FROM middleman_stack_members
WHERE stack_id = ?1
`

func (q *Queries) DeleteStackMembersByStack(ctx context.Context, stackID int64) error {
	_, err := q.db.ExecContext(ctx, deleteStackMembersByStack, stackID)
	return err
}

const deleteStaleStacksForRepo = `-- name: DeleteStaleStacksForRepo :exec
DELETE FROM middleman_stacks
WHERE repo_id = ?1
  AND id NOT IN (/*SLICE:active_stack_ids*/?)
`

type DeleteStaleStacksForRepoParams struct {
	RepoID         int64
	ActiveStackIds []int64
}

func (q *Queries) DeleteStaleStacksForRepo(ctx context.Context, arg DeleteStaleStacksForRepoParams) error {
	query := deleteStaleStacksForRepo
	var queryParams []interface{}
	queryParams = append(queryParams, arg.RepoID)
	if len(arg.ActiveStackIds) > 0 {
		for _, v := range arg.ActiveStackIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:active_stack_ids*/?", strings.Repeat(",?", len(arg.ActiveStackIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:active_stack_ids*/?", "NULL", 1)
	}
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}

const getStackForPR = `-- name: GetStackForPR :one
SELECT s.id, s.repo_id, s.base_number, s.name, s.created_at, s.updated_at
FROM middleman_stacks s
JOIN middleman_stack_members sm ON sm.stack_id = s.id
JOIN middleman_merge_requests p ON p.id = sm.merge_request_id
JOIN middleman_repos r ON r.id = p.repo_id
WHERE r.owner = ?1
  AND r.name = ?2
  AND p.number = ?3
`

type GetStackForPRParams struct {
	Owner  string
	Name   string
	Number int64
}

func (q *Queries) GetStackForPR(ctx context.Context, arg GetStackForPRParams) (MiddlemanStack, error) {
	row := q.db.QueryRowContext(ctx, getStackForPR, arg.Owner, arg.Name, arg.Number)
	var i MiddlemanStack
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.BaseNumber,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertStackMember = `-- name: InsertStackMember :exec
INSERT INTO middleman_stack_members (stack_id, merge_request_id, position)
VALUES (?1, ?2, ?3)
`

type InsertStackMemberParams struct {
	StackID        int64
	MergeRequestID int64
	Position       int64
}

func (q *Queries) InsertStackMember(ctx context.Context, arg InsertStackMemberParams) error {
	_, err := q.db.ExecContext(ctx, insertStackMember, arg.StackID, arg.MergeRequestID, arg.Position)
	return err
}

const listPRsForStackDetection = `-- name: ListPRsForStackDetection :many
SELECT id, number, title, head_branch, base_branch, state, ci_status, review_decision
FROM middleman_merge_requests
WHERE repo_id = ?1 AND state IN ('open', 'merged')
ORDER BY number
`

type ListPRsForStackDetectionRow struct {
	ID             int64
	Number         int64
	Title          string
	HeadBranch     string
	BaseBranch     string
	State          string
	CiStatus       string
	ReviewDecision string
}

func (q *Queries) ListPRsForStackDetection(ctx context.Context, repoID int64) ([]ListPRsForStackDetectionRow, error) {
	rows, err := q.db.QueryContext(ctx, listPRsForStackDetection, repoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPRsForStackDetectionRow
	for rows.Next() {
		var i ListPRsForStackDetectionRow
		if err := rows.Scan(
			&i.ID,
			&i.Number,
			&i.Title,
			&i.HeadBranch,
			&i.BaseBranch,
			&i.State,
			&i.CiStatus,
			&i.ReviewDecision,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStackMembersByStack = `-- name: ListStackMembersByStack :many
SELECT sm.stack_id, sm.merge_request_id, sm.position,
       p.number, p.title, p.state, p.ci_status, p.review_decision,
       p.is_draft, p.base_branch
FROM middleman_stack_members sm
JOIN middleman_merge_requests p ON p.id = sm.merge_request_id
WHERE sm.stack_id = ?1
ORDER BY sm.position
`

type ListStackMembersByStackRow struct {
	StackID        int64
	MergeRequestID int64
	Position       int64
	Number         int64
	Title          string
	State          string
	CiStatus       string
	ReviewDecision string
	IsDraft        int64
	BaseBranch     string
}

func (q *Queries) ListStackMembersByStack(ctx context.Context, stackID int64) ([]ListStackMembersByStackRow, error) {
	rows, err := q.db.QueryContext(ctx, listStackMembersByStack, stackID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStackMembersByStackRow
	for rows.Next() {
		var i ListStackMembersByStackRow
		if err := rows.Scan(
			&i.StackID,
			&i.MergeRequestID,
			&i.Position,
			&i.Number,
			&i.Title,
			&i.State,
			&i.CiStatus,
			&i.ReviewDecision,
			&i.IsDraft,
			&i.BaseBranch,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStackMembersByStackIDs = `-- name: ListStackMembersByStackIDs :many
SELECT sm.stack_id, sm.merge_request_id, sm.position,
       p.number, p.title, p.state, p.ci_status, p.review_decision,
       p.is_draft, p.base_branch
FROM middleman_stack_members sm
JOIN middleman_merge_requests p ON p.id = sm.merge_request_id
WHERE sm.stack_id IN (/*SLICE:stack_ids*/?)
ORDER BY sm.stack_id, sm.position
`

type ListStackMembersByStackIDsRow struct {
	StackID        int64
	MergeRequestID int64
	Position       int64
	Number         int64
	Title          string
	State          string
	CiStatus       string
	ReviewDecision string
	IsDraft        int64
	BaseBranch     string
}

func (q *Queries) ListStackMembersByStackIDs(ctx context.Context, stackIds []int64) ([]ListStackMembersByStackIDsRow, error) {
	query := listStackMembersByStackIDs
	var queryParams []interface{}
	if len(stackIds) > 0 {
		for _, v := range stackIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:stack_ids*/?", strings.Repeat(",?", len(stackIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:stack_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStackMembersByStackIDsRow
	for rows.Next() {
		var i ListStackMembersByStackIDsRow
		if err := rows.Scan(
			&i.StackID,
			&i.MergeRequestID,
			&i.Position,
			&i.Number,
			&i.Title,
			&i.State,
			&i.CiStatus,
			&i.ReviewDecision,
			&i.IsDraft,
			&i.BaseBranch,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStacksWithOpenMembers = `-- name: ListStacksWithOpenMembers :many
SELECT s.id, s.repo_id, s.base_number, s.name, s.created_at, s.updated_at,
       r.owner, r.name AS repo_name
FROM middleman_stacks s
JOIN middleman_repos r ON r.id = s.repo_id
WHERE EXISTS (
    SELECT 1 FROM middleman_stack_members sm2
    JOIN middleman_merge_requests p2 ON p2.id = sm2.merge_request_id
    WHERE sm2.stack_id = s.id AND p2.state = 'open'
)
ORDER BY s.updated_at DESC
`

type ListStacksWithOpenMembersRow struct {
	ID         int64
	RepoID     int64
	BaseNumber int64
	Name       string
	CreatedAt  time.Time
	UpdatedAt  time.Time
	Owner      string
	RepoName   string
}

func (q *Queries) ListStacksWithOpenMembers(ctx context.Context) ([]ListStacksWithOpenMembersRow, error) {
	rows, err := q.db.QueryContext(ctx, listStacksWithOpenMembers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStacksWithOpenMembersRow
	for rows.Next() {
		var i ListStacksWithOpenMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.BaseNumber,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Owner,
			&i.RepoName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStacksWithOpenMembersByRepo = `-- name: ListStacksWithOpenMembersByRepo :many
SELECT s.id, s.repo_id, s.base_number, s.name, s.created_at, s.updated_at,
       r.owner, r.name AS repo_name
FROM middleman_stacks s
JOIN middleman_repos r ON r.id = s.repo_id
WHERE r.owner = ?1
  AND r.name = ?2
  AND EXISTS (
      SELECT 1 FROM middleman_stack_members sm2
      JOIN middleman_merge_requests p2 ON p2.id = sm2.merge_request_id
      WHERE sm2.stack_id = s.id AND p2.state = 'open'
  )
ORDER BY s.updated_at DESC
`

type ListStacksWithOpenMembersByRepoParams struct {
	Owner string
	Name  string
}

type ListStacksWithOpenMembersByRepoRow struct {
	ID         int64
	RepoID     int64
	BaseNumber int64
	Name       string
	CreatedAt  time.Time
	UpdatedAt  time.Time
	Owner      string
	RepoName   string
}

func (q *Queries) ListStacksWithOpenMembersByRepo(ctx context.Context, arg ListStacksWithOpenMembersByRepoParams) ([]ListStacksWithOpenMembersByRepoRow, error) {
	rows, err := q.db.QueryContext(ctx, listStacksWithOpenMembersByRepo, arg.Owner, arg.Name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStacksWithOpenMembersByRepoRow
	for rows.Next() {
		var i ListStacksWithOpenMembersByRepoRow
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.BaseNumber,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Owner,
			&i.RepoName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertStack = `-- name: UpsertStack :one
INSERT INTO middleman_stacks (repo_id, base_number, name)
VALUES (?1, ?2, ?3)
ON CONFLICT(repo_id, base_number) DO UPDATE SET
    name = excluded.name,
    updated_at = datetime('now')
RETURNING id
`

type UpsertStackParams struct {
	RepoID     int64
	BaseNumber int64
	Name       string
}

func (q *Queries) UpsertStack(ctx context.Context, arg UpsertStackParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, upsertStack, arg.RepoID, arg.BaseNumber, arg.Name)
	var id int64
	err := row.Scan(&id)
	return id, err
}
