// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stars.sql

package sqlc

import (
	"context"
)

const isStarred = `-- name: IsStarred :one
SELECT EXISTS (
    SELECT 1
    FROM middleman_starred_items
    WHERE item_type = ?1
      AND repo_id = ?2
      AND number = ?3
)
`

type IsStarredParams struct {
	ItemType string
	RepoID   int64
	Number   int64
}

func (q *Queries) IsStarred(ctx context.Context, arg IsStarredParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, isStarred, arg.ItemType, arg.RepoID, arg.Number)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const setStarred = `-- name: SetStarred :exec
INSERT INTO middleman_starred_items (item_type, repo_id, number)
VALUES (?1, ?2, ?3)
ON CONFLICT(item_type, repo_id, number) DO NOTHING
`

type SetStarredParams struct {
	ItemType string
	RepoID   int64
	Number   int64
}

func (q *Queries) SetStarred(ctx context.Context, arg SetStarredParams) error {
	_, err := q.db.ExecContext(ctx, setStarred, arg.ItemType, arg.RepoID, arg.Number)
	return err
}

const unsetStarred = `-- name: UnsetStarred :exec
DELETE FROM middleman_starred_items
WHERE item_type = ?1
  AND repo_id = ?2
  AND number = ?3
`

type UnsetStarredParams struct {
	ItemType string
	RepoID   int64
	Number   int64
}

func (q *Queries) UnsetStarred(ctx context.Context, arg UnsetStarredParams) error {
	_, err := q.db.ExecContext(ctx, unsetStarred, arg.ItemType, arg.RepoID, arg.Number)
	return err
}
