// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workspaces.sql

package sqlc

import (
	"context"
	"database/sql"
	"strings"
	"time"
)

const deleteAllWorktreeLinks = `-- name: DeleteAllWorktreeLinks :exec
DELETE FROM middleman_mr_worktree_links
`

func (q *Queries) DeleteAllWorktreeLinks(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllWorktreeLinks)
	return err
}

const deleteWorkspace = `-- name: DeleteWorkspace :exec
DELETE FROM middleman_workspaces
WHERE id = ?1
`

func (q *Queries) DeleteWorkspace(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteWorkspace, id)
	return err
}

const deleteWorkspaceTmuxSession = `-- name: DeleteWorkspaceTmuxSession :exec
DELETE FROM middleman_workspace_tmux_sessions
WHERE workspace_id = ?1
  AND session_name = ?2
`

type DeleteWorkspaceTmuxSessionParams struct {
	WorkspaceID string
	SessionName string
}

func (q *Queries) DeleteWorkspaceTmuxSession(ctx context.Context, arg DeleteWorkspaceTmuxSessionParams) error {
	_, err := q.db.ExecContext(ctx, deleteWorkspaceTmuxSession, arg.WorkspaceID, arg.SessionName)
	return err
}

const deleteWorkspaceTmuxSessionCreatedAt = `-- name: DeleteWorkspaceTmuxSessionCreatedAt :execrows
DELETE FROM middleman_workspace_tmux_sessions
WHERE workspace_id = ?1
  AND session_name = ?2
  AND created_at = ?3
`

type DeleteWorkspaceTmuxSessionCreatedAtParams struct {
	WorkspaceID string
	SessionName string
	CreatedAt   time.Time
}

func (q *Queries) DeleteWorkspaceTmuxSessionCreatedAt(ctx context.Context, arg DeleteWorkspaceTmuxSessionCreatedAtParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteWorkspaceTmuxSessionCreatedAt, arg.WorkspaceID, arg.SessionName, arg.CreatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteWorkspaceTmuxSessions = `-- name: DeleteWorkspaceTmuxSessions :exec
DELETE FROM middleman_workspace_tmux_sessions
WHERE workspace_id = ?1
`

func (q *Queries) DeleteWorkspaceTmuxSessions(ctx context.Context, workspaceID string) error {
	_, err := q.db.ExecContext(ctx, deleteWorkspaceTmuxSessions, workspaceID)
	return err
}

const getWorkspace = `-- name: GetWorkspace :one
SELECT id, platform_host, repo_owner, repo_name,
       item_type, item_number, associated_pr_number,
       git_head_ref, mr_head_repo, workspace_branch,
       worktree_path, tmux_session, status,
       error_message, created_at
FROM middleman_workspaces
WHERE id = ?1
`

type GetWorkspaceRow struct {
	ID                 string
	PlatformHost       string
	RepoOwner          string
	RepoName           string
	ItemType           string
	ItemNumber         int64
	AssociatedPrNumber sql.NullInt64
	GitHeadRef         string
	MrHeadRepo         sql.NullString
	WorkspaceBranch    string
	WorktreePath       string
	TmuxSession        string
	Status             string
	ErrorMessage       sql.NullString
	CreatedAt          time.Time
}

func (q *Queries) GetWorkspace(ctx context.Context, id string) (GetWorkspaceRow, error) {
	row := q.db.QueryRowContext(ctx, getWorkspace, id)
	var i GetWorkspaceRow
	err := row.Scan(
		&i.ID,
		&i.PlatformHost,
		&i.RepoOwner,
		&i.RepoName,
		&i.ItemType,
		&i.ItemNumber,
		&i.AssociatedPrNumber,
		&i.GitHeadRef,
		&i.MrHeadRepo,
		&i.WorkspaceBranch,
		&i.WorktreePath,
		&i.TmuxSession,
		&i.Status,
		&i.ErrorMessage,
		&i.CreatedAt,
	)
	return i, err
}

const getWorkspaceByItem = `-- name: GetWorkspaceByItem :one
SELECT id, platform_host, repo_owner, repo_name,
       item_type, item_number, associated_pr_number,
       git_head_ref, mr_head_repo, workspace_branch,
       worktree_path, tmux_session, status,
       error_message, created_at
FROM middleman_workspaces
WHERE platform_host = ?1
  AND repo_owner = ?2
  AND repo_name = ?3
  AND item_type = ?4
  AND item_number = ?5
`

type GetWorkspaceByItemParams struct {
	PlatformHost string
	RepoOwner    string
	RepoName     string
	ItemType     string
	ItemNumber   int64
}

type GetWorkspaceByItemRow struct {
	ID                 string
	PlatformHost       string
	RepoOwner          string
	RepoName           string
	ItemType           string
	ItemNumber         int64
	AssociatedPrNumber sql.NullInt64
	GitHeadRef         string
	MrHeadRepo         sql.NullString
	WorkspaceBranch    string
	WorktreePath       string
	TmuxSession        string
	Status             string
	ErrorMessage       sql.NullString
	CreatedAt          time.Time
}

func (q *Queries) GetWorkspaceByItem(ctx context.Context, arg GetWorkspaceByItemParams) (GetWorkspaceByItemRow, error) {
	row := q.db.QueryRowContext(ctx, getWorkspaceByItem,
		arg.PlatformHost,
		arg.RepoOwner,
		arg.RepoName,
		arg.ItemType,
		arg.ItemNumber,
	)
	var i GetWorkspaceByItemRow
	err := row.Scan(
		&i.ID,
		&i.PlatformHost,
		&i.RepoOwner,
		&i.RepoName,
		&i.ItemType,
		&i.ItemNumber,
		&i.AssociatedPrNumber,
		&i.GitHeadRef,
		&i.MrHeadRepo,
		&i.WorkspaceBranch,
		&i.WorktreePath,
		&i.TmuxSession,
		&i.Status,
		&i.ErrorMessage,
		&i.CreatedAt,
	)
	return i, err
}

const getWorkspaceSummary = `-- name: GetWorkspaceSummary :one
SELECT
    w.id, w.platform_host, w.repo_owner, w.repo_name,
    w.item_type, w.item_number, w.associated_pr_number,
    w.git_head_ref, w.mr_head_repo, w.workspace_branch,
    w.worktree_path, w.tmux_session, w.status,
    w.error_message, w.created_at,
    CASE
        WHEN w.item_type = 'issue' THEN i.title
        ELSE m.title
    END AS mr_title,
    CASE
        WHEN w.item_type = 'issue' THEN i.state
        ELSE m.state
    END AS mr_state,
    m.is_draft AS mr_is_draft,
    m.ci_status AS mr_ci_status,
    m.review_decision AS mr_review_decision,
    m.additions AS mr_additions,
    m.deletions AS mr_deletions
FROM middleman_workspaces w
LEFT JOIN middleman_repos r
    ON r.platform_host = w.platform_host
   AND r.owner = w.repo_owner
   AND r.name = w.repo_name
LEFT JOIN middleman_merge_requests m
    ON m.repo_id = r.id
   AND m.number = w.item_number
   AND w.item_type = 'pull_request'
LEFT JOIN middleman_issues i
    ON i.repo_id = r.id
   AND i.number = w.item_number
   AND w.item_type = 'issue'
WHERE w.id = ?1
`

type GetWorkspaceSummaryRow struct {
	ID                 string
	PlatformHost       string
	RepoOwner          string
	RepoName           string
	ItemType           string
	ItemNumber         int64
	AssociatedPrNumber sql.NullInt64
	GitHeadRef         string
	MrHeadRepo         sql.NullString
	WorkspaceBranch    string
	WorktreePath       string
	TmuxSession        string
	Status             string
	ErrorMessage       sql.NullString
	CreatedAt          time.Time
	MrTitle            interface{}
	MrState            interface{}
	MrIsDraft          sql.NullInt64
	MrCiStatus         sql.NullString
	MrReviewDecision   sql.NullString
	MrAdditions        sql.NullInt64
	MrDeletions        sql.NullInt64
}

func (q *Queries) GetWorkspaceSummary(ctx context.Context, id string) (GetWorkspaceSummaryRow, error) {
	row := q.db.QueryRowContext(ctx, getWorkspaceSummary, id)
	var i GetWorkspaceSummaryRow
	err := row.Scan(
		&i.ID,
		&i.PlatformHost,
		&i.RepoOwner,
		&i.RepoName,
		&i.ItemType,
		&i.ItemNumber,
		&i.AssociatedPrNumber,
		&i.GitHeadRef,
		&i.MrHeadRepo,
		&i.WorkspaceBranch,
		&i.WorktreePath,
		&i.TmuxSession,
		&i.Status,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.MrTitle,
		&i.MrState,
		&i.MrIsDraft,
		&i.MrCiStatus,
		&i.MrReviewDecision,
		&i.MrAdditions,
		&i.MrDeletions,
	)
	return i, err
}

const insertWorkspace = `-- name: InsertWorkspace :exec
INSERT INTO middleman_workspaces (
    id, platform_host, repo_owner, repo_name,
    item_type, item_number, associated_pr_number,
    git_head_ref, mr_head_repo, workspace_branch,
    worktree_path, tmux_session, status,
    error_message
)
VALUES (
    ?1, ?2, ?3, ?4,
    ?5, ?6, ?7,
    ?8, ?9, ?10,
    ?11, ?12, ?13,
    ?14
)
`

type InsertWorkspaceParams struct {
	ID                 string
	PlatformHost       string
	RepoOwner          string
	RepoName           string
	ItemType           string
	ItemNumber         int64
	AssociatedPrNumber sql.NullInt64
	GitHeadRef         string
	MrHeadRepo         sql.NullString
	WorkspaceBranch    string
	WorktreePath       string
	TmuxSession        string
	Status             string
	ErrorMessage       sql.NullString
}

func (q *Queries) InsertWorkspace(ctx context.Context, arg InsertWorkspaceParams) error {
	_, err := q.db.ExecContext(ctx, insertWorkspace,
		arg.ID,
		arg.PlatformHost,
		arg.RepoOwner,
		arg.RepoName,
		arg.ItemType,
		arg.ItemNumber,
		arg.AssociatedPrNumber,
		arg.GitHeadRef,
		arg.MrHeadRepo,
		arg.WorkspaceBranch,
		arg.WorktreePath,
		arg.TmuxSession,
		arg.Status,
		arg.ErrorMessage,
	)
	return err
}

const insertWorkspaceSetupEvent = `-- name: InsertWorkspaceSetupEvent :exec
INSERT INTO middleman_workspace_setup_events (
    workspace_id, stage, outcome, message
)
VALUES (
    ?1, ?2, ?3, ?4
)
`

type InsertWorkspaceSetupEventParams struct {
	WorkspaceID string
	Stage       string
	Outcome     string
	Message     string
}

func (q *Queries) InsertWorkspaceSetupEvent(ctx context.Context, arg InsertWorkspaceSetupEventParams) error {
	_, err := q.db.ExecContext(ctx, insertWorkspaceSetupEvent,
		arg.WorkspaceID,
		arg.Stage,
		arg.Outcome,
		arg.Message,
	)
	return err
}

const insertWorktreeLink = `-- name: InsertWorktreeLink :exec
INSERT INTO middleman_mr_worktree_links (
    merge_request_id, worktree_key, worktree_path, worktree_branch, linked_at
)
VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5
)
`

type InsertWorktreeLinkParams struct {
	MergeRequestID int64
	WorktreeKey    string
	WorktreePath   sql.NullString
	WorktreeBranch sql.NullString
	LinkedAt       string
}

func (q *Queries) InsertWorktreeLink(ctx context.Context, arg InsertWorktreeLinkParams) error {
	_, err := q.db.ExecContext(ctx, insertWorktreeLink,
		arg.MergeRequestID,
		arg.WorktreeKey,
		arg.WorktreePath,
		arg.WorktreeBranch,
		arg.LinkedAt,
	)
	return err
}

const listAllWorkspaceTmuxSessions = `-- name: ListAllWorkspaceTmuxSessions :many
SELECT workspace_id, session_name, target_key, created_at
FROM middleman_workspace_tmux_sessions
ORDER BY workspace_id, target_key, created_at, session_name
`

func (q *Queries) ListAllWorkspaceTmuxSessions(ctx context.Context) ([]MiddlemanWorkspaceTmuxSession, error) {
	rows, err := q.db.QueryContext(ctx, listAllWorkspaceTmuxSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MiddlemanWorkspaceTmuxSession
	for rows.Next() {
		var i MiddlemanWorkspaceTmuxSession
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.SessionName,
			&i.TargetKey,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllWorktreeLinks = `-- name: ListAllWorktreeLinks :many
SELECT id, merge_request_id, worktree_key,
       worktree_path, worktree_branch, linked_at
FROM middleman_mr_worktree_links
ORDER BY linked_at DESC
`

func (q *Queries) ListAllWorktreeLinks(ctx context.Context) ([]MiddlemanMrWorktreeLink, error) {
	rows, err := q.db.QueryContext(ctx, listAllWorktreeLinks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MiddlemanMrWorktreeLink
	for rows.Next() {
		var i MiddlemanMrWorktreeLink
		if err := rows.Scan(
			&i.ID,
			&i.MergeRequestID,
			&i.WorktreeKey,
			&i.WorktreePath,
			&i.WorktreeBranch,
			&i.LinkedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaceSetupEvents = `-- name: ListWorkspaceSetupEvents :many
SELECT id, workspace_id, stage, outcome, message, created_at
FROM middleman_workspace_setup_events
WHERE workspace_id = ?1
ORDER BY id
`

func (q *Queries) ListWorkspaceSetupEvents(ctx context.Context, workspaceID string) ([]MiddlemanWorkspaceSetupEvent, error) {
	rows, err := q.db.QueryContext(ctx, listWorkspaceSetupEvents, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MiddlemanWorkspaceSetupEvent
	for rows.Next() {
		var i MiddlemanWorkspaceSetupEvent
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Stage,
			&i.Outcome,
			&i.Message,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaceSummaries = `-- name: ListWorkspaceSummaries :many
SELECT
    w.id, w.platform_host, w.repo_owner, w.repo_name,
    w.item_type, w.item_number, w.associated_pr_number,
    w.git_head_ref, w.mr_head_repo, w.workspace_branch,
    w.worktree_path, w.tmux_session, w.status,
    w.error_message, w.created_at,
    CASE
        WHEN w.item_type = 'issue' THEN i.title
        ELSE m.title
    END AS mr_title,
    CASE
        WHEN w.item_type = 'issue' THEN i.state
        ELSE m.state
    END AS mr_state,
    m.is_draft AS mr_is_draft,
    m.ci_status AS mr_ci_status,
    m.review_decision AS mr_review_decision,
    m.additions AS mr_additions,
    m.deletions AS mr_deletions
FROM middleman_workspaces w
LEFT JOIN middleman_repos r
    ON r.platform_host = w.platform_host
   AND r.owner = w.repo_owner
   AND r.name = w.repo_name
LEFT JOIN middleman_merge_requests m
    ON m.repo_id = r.id
   AND m.number = w.item_number
   AND w.item_type = 'pull_request'
LEFT JOIN middleman_issues i
    ON i.repo_id = r.id
   AND i.number = w.item_number
   AND w.item_type = 'issue'
ORDER BY w.created_at DESC
`

type ListWorkspaceSummariesRow struct {
	ID                 string
	PlatformHost       string
	RepoOwner          string
	RepoName           string
	ItemType           string
	ItemNumber         int64
	AssociatedPrNumber sql.NullInt64
	GitHeadRef         string
	MrHeadRepo         sql.NullString
	WorkspaceBranch    string
	WorktreePath       string
	TmuxSession        string
	Status             string
	ErrorMessage       sql.NullString
	CreatedAt          time.Time
	MrTitle            interface{}
	MrState            interface{}
	MrIsDraft          sql.NullInt64
	MrCiStatus         sql.NullString
	MrReviewDecision   sql.NullString
	MrAdditions        sql.NullInt64
	MrDeletions        sql.NullInt64
}

func (q *Queries) ListWorkspaceSummaries(ctx context.Context) ([]ListWorkspaceSummariesRow, error) {
	rows, err := q.db.QueryContext(ctx, listWorkspaceSummaries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWorkspaceSummariesRow
	for rows.Next() {
		var i ListWorkspaceSummariesRow
		if err := rows.Scan(
			&i.ID,
			&i.PlatformHost,
			&i.RepoOwner,
			&i.RepoName,
			&i.ItemType,
			&i.ItemNumber,
			&i.AssociatedPrNumber,
			&i.GitHeadRef,
			&i.MrHeadRepo,
			&i.WorkspaceBranch,
			&i.WorktreePath,
			&i.TmuxSession,
			&i.Status,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.MrTitle,
			&i.MrState,
			&i.MrIsDraft,
			&i.MrCiStatus,
			&i.MrReviewDecision,
			&i.MrAdditions,
			&i.MrDeletions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaceTmuxSessions = `-- name: ListWorkspaceTmuxSessions :many
SELECT workspace_id, session_name, target_key, created_at
FROM middleman_workspace_tmux_sessions
WHERE workspace_id = ?1
ORDER BY target_key, created_at, session_name
`

func (q *Queries) ListWorkspaceTmuxSessions(ctx context.Context, workspaceID string) ([]MiddlemanWorkspaceTmuxSession, error) {
	rows, err := q.db.QueryContext(ctx, listWorkspaceTmuxSessions, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MiddlemanWorkspaceTmuxSession
	for rows.Next() {
		var i MiddlemanWorkspaceTmuxSession
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.SessionName,
			&i.TargetKey,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaces = `-- name: ListWorkspaces :many
SELECT id, platform_host, repo_owner, repo_name,
       item_type, item_number, associated_pr_number,
       git_head_ref, mr_head_repo, workspace_branch,
       worktree_path, tmux_session, status,
       error_message, created_at
FROM middleman_workspaces
ORDER BY created_at DESC
`

type ListWorkspacesRow struct {
	ID                 string
	PlatformHost       string
	RepoOwner          string
	RepoName           string
	ItemType           string
	ItemNumber         int64
	AssociatedPrNumber sql.NullInt64
	GitHeadRef         string
	MrHeadRepo         sql.NullString
	WorkspaceBranch    string
	WorktreePath       string
	TmuxSession        string
	Status             string
	ErrorMessage       sql.NullString
	CreatedAt          time.Time
}

func (q *Queries) ListWorkspaces(ctx context.Context) ([]ListWorkspacesRow, error) {
	rows, err := q.db.QueryContext(ctx, listWorkspaces)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWorkspacesRow
	for rows.Next() {
		var i ListWorkspacesRow
		if err := rows.Scan(
			&i.ID,
			&i.PlatformHost,
			&i.RepoOwner,
			&i.RepoName,
			&i.ItemType,
			&i.ItemNumber,
			&i.AssociatedPrNumber,
			&i.GitHeadRef,
			&i.MrHeadRepo,
			&i.WorkspaceBranch,
			&i.WorktreePath,
			&i.TmuxSession,
			&i.Status,
			&i.ErrorMessage,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorktreeLinksForMR = `-- name: ListWorktreeLinksForMR :many
SELECT id, merge_request_id, worktree_key,
       worktree_path, worktree_branch, linked_at
FROM middleman_mr_worktree_links
WHERE merge_request_id = ?1
ORDER BY linked_at DESC
`

func (q *Queries) ListWorktreeLinksForMR(ctx context.Context, mergeRequestID int64) ([]MiddlemanMrWorktreeLink, error) {
	rows, err := q.db.QueryContext(ctx, listWorktreeLinksForMR, mergeRequestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MiddlemanMrWorktreeLink
	for rows.Next() {
		var i MiddlemanMrWorktreeLink
		if err := rows.Scan(
			&i.ID,
			&i.MergeRequestID,
			&i.WorktreeKey,
			&i.WorktreePath,
			&i.WorktreeBranch,
			&i.LinkedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorktreeLinksForMRIDs = `-- name: ListWorktreeLinksForMRIDs :many
SELECT id, merge_request_id, worktree_key,
       worktree_path, worktree_branch, linked_at
FROM middleman_mr_worktree_links
WHERE merge_request_id IN (/*SLICE:merge_request_ids*/?)
ORDER BY linked_at DESC
`

func (q *Queries) ListWorktreeLinksForMRIDs(ctx context.Context, mergeRequestIds []int64) ([]MiddlemanMrWorktreeLink, error) {
	query := listWorktreeLinksForMRIDs
	var queryParams []interface{}
	if len(mergeRequestIds) > 0 {
		for _, v := range mergeRequestIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:merge_request_ids*/?", strings.Repeat(",?", len(mergeRequestIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:merge_request_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MiddlemanMrWorktreeLink
	for rows.Next() {
		var i MiddlemanMrWorktreeLink
		if err := rows.Scan(
			&i.ID,
			&i.MergeRequestID,
			&i.WorktreeKey,
			&i.WorktreePath,
			&i.WorktreeBranch,
			&i.LinkedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setWorkspaceAssociatedPRNumberIfNull = `-- name: SetWorkspaceAssociatedPRNumberIfNull :execrows
UPDATE middleman_workspaces
SET associated_pr_number = ?1
WHERE id = ?2 AND associated_pr_number IS NULL
`

type SetWorkspaceAssociatedPRNumberIfNullParams struct {
	AssociatedPrNumber sql.NullInt64
	ID                 string
}

func (q *Queries) SetWorkspaceAssociatedPRNumberIfNull(ctx context.Context, arg SetWorkspaceAssociatedPRNumberIfNullParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setWorkspaceAssociatedPRNumberIfNull, arg.AssociatedPrNumber, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const startWorkspaceRetry = `-- name: StartWorkspaceRetry :execrows
UPDATE middleman_workspaces
SET status = 'creating',
    error_message = NULL
WHERE id = ?1 AND status = 'error'
`

func (q *Queries) StartWorkspaceRetry(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, startWorkspaceRetry, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateWorkspaceBranch = `-- name: UpdateWorkspaceBranch :exec
UPDATE middleman_workspaces
SET workspace_branch = ?1
WHERE id = ?2
`

type UpdateWorkspaceBranchParams struct {
	WorkspaceBranch string
	ID              string
}

func (q *Queries) UpdateWorkspaceBranch(ctx context.Context, arg UpdateWorkspaceBranchParams) error {
	_, err := q.db.ExecContext(ctx, updateWorkspaceBranch, arg.WorkspaceBranch, arg.ID)
	return err
}

const updateWorkspaceStatus = `-- name: UpdateWorkspaceStatus :exec
UPDATE middleman_workspaces
SET status = ?1,
    error_message = ?2
WHERE id = ?3
`

type UpdateWorkspaceStatusParams struct {
	Status       string
	ErrorMessage sql.NullString
	ID           string
}

func (q *Queries) UpdateWorkspaceStatus(ctx context.Context, arg UpdateWorkspaceStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateWorkspaceStatus, arg.Status, arg.ErrorMessage, arg.ID)
	return err
}

const upsertWorkspaceTmuxSession = `-- name: UpsertWorkspaceTmuxSession :exec
INSERT INTO middleman_workspace_tmux_sessions (
    workspace_id, session_name, target_key, created_at
)
VALUES (
    ?1, ?2, ?3, ?4
)
ON CONFLICT(workspace_id, session_name) DO UPDATE SET
    target_key = excluded.target_key,
    created_at = excluded.created_at
`

type UpsertWorkspaceTmuxSessionParams struct {
	WorkspaceID string
	SessionName string
	TargetKey   string
	CreatedAt   time.Time
}

func (q *Queries) UpsertWorkspaceTmuxSession(ctx context.Context, arg UpsertWorkspaceTmuxSessionParams) error {
	_, err := q.db.ExecContext(ctx, upsertWorkspaceTmuxSession,
		arg.WorkspaceID,
		arg.SessionName,
		arg.TargetKey,
		arg.CreatedAt,
	)
	return err
}
